// ============================================================================
// KOI - Compile the category tree into the module the code reads
//
// Phase 2.3. The tree lives in the database: food.taxonomy_node,
// food.taxonomy_term and food.portion_norm. The storefront places products in
// the browser and the screening job on the server, so both read a compiled
// copy: src/lib/food/taxonomyData.js. This writes it, stamped with a hash of
// its contents; --check fails if it no longer matches the database.
//
// The build fails, rather than guessing, when two categories claim the same
// name once normalised, or when a label could read as a claim.
//
// Usage, from web/:
//   node --import ./scripts/testAlias.mjs --env-file=.env.local scripts/buildTaxonomy.mjs          write the file
//   node --import ./scripts/testAlias.mjs --env-file=.env.local scripts/buildTaxonomy.mjs --check  fail if it is stale
// ============================================================================

import fs from "node:fs";
import path from "node:path";
import { createHash } from "node:crypto";
import { normalise } from "@/lib/food/normalise.js";
import { isClaimSafeText } from "@/lib/nutrition/claims.js";

const CHECK = process.argv.includes("--check");
const OUT = path.resolve(process.cwd(), "src", "lib", "food", "taxonomyData.js");

const BASE = process.env.NEXT_PUBLIC_SUPABASE_URL?.replace(/\/$/, "");
const KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;
if (!BASE || !KEY) {
  console.error("Missing NEXT_PUBLIC_SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY. Run with --env-file=.env.local from web/.");
  process.exit(1);
}

async function read(query) {
  const res = await fetch(`${BASE}/rest/v1/${query}`, {
    headers: { apikey: KEY, Authorization: `Bearer ${KEY}`, "Accept-Profile": "food" },
  });
  if (!res.ok) throw new Error(`food.${query.split("?")[0]} -> ${res.status} ${(await res.text()).slice(0, 200)}`);
  return res.json();
}

const [nodes, terms, portions] = await Promise.all([
  read("taxonomy_node?select=key,parent_key,label&order=key"),
  read("taxonomy_term?select=term,node_key,kind&order=term"),
  read("portion_norm?select=node_key,reference_amount,unit,plausible_max,household_measure&order=node_key"),
]);

const problems = [];
for (const n of nodes) {
  if (!isClaimSafeText(n.label)) problems.push(`label "${n.label}" (${n.key}) reads as a claim`);
}

// A name's owner is its category and its kind (form, ingredient, marker,
// ignore); two different owners for one normalised name is ambiguous.
const owners = new Map();
for (const { term, node_key: key, kind } of terms) {
  const name = normalise(term);
  if (!name) continue;
  const owner = `${key ?? ""}|${kind}`;
  if (owners.has(name) && owners.get(name) !== owner) {
    problems.push(`"${name}" is both ${owners.get(name)} and ${owner}`);
    continue;
  }
  owners.set(name, owner);
}
if (problems.length) {
  console.error(`The category tree cannot be compiled:\n  ${problems.join("\n  ")}`);
  process.exit(1);
}

const NODES = Object.fromEntries(nodes.map((n) => [n.key, { label: n.label, parent: n.parent_key }]));
const TERMS = [...owners.entries()]
  .sort((a, b) => a[0].localeCompare(b[0]))
  .map(([name, owner]) => {
    const [key, kind] = owner.split("|");
    return [name, key || null, kind];
  });
const PORTIONS = Object.fromEntries(portions.map((p) => [p.node_key, {
  amount: Number(p.reference_amount),
  unit: p.unit,
  max: Number(p.plausible_max),
  measure: p.household_measure,
}]));

const data = { NODES, TERMS, PORTIONS };
const version = createHash("sha256").update(JSON.stringify(data)).digest("hex").slice(0, 12);

const file = `// ============================================================================
// GENERATED by scripts/buildTaxonomy.mjs from food.taxonomy_node,
// food.taxonomy_term and food.portion_norm. Do not edit by hand: change the
// tree in the database, then rebuild.
// ${nodes.length} categories, ${TERMS.length} names, ${portions.length} reference portions.
// ============================================================================

export const TAXONOMY_VERSION = ${JSON.stringify(version)};

// key -> { label, parent }
export const NODES = ${JSON.stringify(NODES, null, 2)};

// [normalised name, category key or null, kind: form | ingredient | marker | ignore]
export const TERMS = ${JSON.stringify(TERMS)};

// category key -> { amount, unit, max, measure }: 21 CFR 101.12 reference amounts
export const PORTIONS = ${JSON.stringify(PORTIONS, null, 2)};
`;

if (CHECK) {
  const current = fs.existsSync(OUT) ? fs.readFileSync(OUT, "utf8") : "";
  if (current !== file) {
    console.error(`src/lib/food/taxonomyData.js is stale (tree version ${version}). Rebuild it.`);
    process.exit(1);
  }
  console.log(`The category tree matches the database (${version}).`);
} else {
  fs.writeFileSync(OUT, file);
  console.log(`Wrote src/lib/food/taxonomyData.js: ${nodes.length} categories, ${TERMS.length} names, ${portions.length} portions, version ${version}.`);
}
