// ============================================================================
// Compile food.dish + food.recipe_line (00068) into src/lib/food/dishData.js
//
//   node --import ./scripts/testAlias.mjs --env-file=.env.local scripts/buildDishes.mjs [--check]
//
// The Plan page's week is built in the browser from this file, the same way
// allergenLexicon.js carries the ingredient graph: the database is the source
// of truth, and a dish's allergens are derived from its lines at runtime
// (lib/food/dishes.js), never stored. --check fails when the file is stale.
// ============================================================================

import fs from "node:fs";
import path from "node:path";
import { createHash } from "node:crypto";

const CHECK = process.argv.includes("--check");
const OUT = path.resolve(process.cwd(), "src", "lib", "food", "dishData.js");
const BASE = process.env.NEXT_PUBLIC_SUPABASE_URL?.replace(/\/$/, "");
const KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;
if (!BASE || !KEY) {
  console.error("Missing NEXT_PUBLIC_SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY. Run with --env-file=.env.local from web/.");
  process.exit(1);
}

async function read(table, select, order) {
  const res = await fetch(`${BASE}/rest/v1/${table}?select=${select}&order=${order}`, {
    headers: { apikey: KEY, Authorization: `Bearer ${KEY}`, "Accept-Profile": "food", Range: "0-4999" },
  });
  if (!res.ok) throw new Error(`food.${table} -> ${res.status} ${(await res.text()).slice(0, 200)}`);
  return res.json();
}

const [dishes, lines, ingredients] = await Promise.all([
  read("dish", "key,name,kind,slots,cuisine,prep_minutes", "key"),
  read("recipe_line", "dish_key,position,ingredient_id,supply,category_key,any_of_shelf,optional,is_blend", "dish_key,position"),
  read("ingredients_master", "id,canonical_name", "canonical_name"),
]);
const nameOf = new Map(ingredients.map((i) => [i.id, i.canonical_name]));

const DISHES = dishes.map((d) => ({
  key: d.key,
  name: d.name,
  kind: d.kind,
  slots: d.slots,
  cuisine: d.cuisine ?? null,
  prepMinutes: d.prep_minutes ?? null,
  lines: lines
    .filter((l) => l.dish_key === d.key)
    .sort((a, b) => a.position - b.position)
    .map((l) => ({
      ingredient: nameOf.get(l.ingredient_id),
      supply: l.supply,
      category: l.category_key ?? null,
      anyOfShelf: l.any_of_shelf,
      optional: l.optional,
      blend: l.is_blend,
    })),
}));

const missing = DISHES.flatMap((d) => d.lines.filter((l) => !l.ingredient).map(() => d.key));
if (missing.length) {
  console.error(`Recipe lines name ingredients that are not in the graph: ${[...new Set(missing)].join(", ")}`);
  process.exit(1);
}

const body = JSON.stringify(DISHES, null, 1);
const version = createHash("sha256").update(body).digest("hex").slice(0, 12);
const file = `// GENERATED by scripts/buildDishes.mjs from food.dish + food.recipe_line (00068). Do not edit.
// A dish is a typical home recipe: what it is made of, and where each part comes
// from (a KOI shelf, fresh, or the kitchen). No quantities — amounts come from
// the planner. Allergens and diet flags are derived at runtime (lib/food/dishes.js).

export const DISH_VERSION = "${version}";

export const DISHES = Object.freeze(${body});
`;

if (CHECK) {
  const current = fs.existsSync(OUT) ? fs.readFileSync(OUT, "utf8") : "";
  if (current.replace(/\r\n/g, "\n") !== file) {
    console.error("src/lib/food/dishData.js is stale: run scripts/buildDishes.mjs.");
    process.exit(1);
  }
  console.log(`dishData.js is current (${DISHES.length} dishes, version ${version}).`);
} else {
  fs.writeFileSync(OUT, file);
  console.log(`Wrote src/lib/food/dishData.js: ${DISHES.length} dishes, ${lines.length} lines, version ${version}.`);
}
