// ============================================================================
// KOI - Compile the processing (NOVA) names into the module the code reads
//
// Phase 2.4. food.processing_names is every label word that signals how a food
// was processed: the terms in food.processing_term, and the names of
// ingredients whose category or additive class decides a role. This writes
// src/lib/food/processingData.js, stamped with a hash of its contents; --check
// fails if it no longer matches the database.
//
// Two names can normalise the same. An explicit term beats a name that came
// from an ingredient; between ingredient names the stronger role wins
// (ultra-processed, then processed, then culinary), so a doubt reads as more
// processed rather than less.
//
// Usage, from web/:
//   node --import ./scripts/testAlias.mjs --env-file=.env.local scripts/buildProcessing.mjs          write the file
//   node --import ./scripts/testAlias.mjs --env-file=.env.local scripts/buildProcessing.mjs --check  fail if it is stale
// ============================================================================

import fs from "node:fs";
import path from "node:path";
import { createHash } from "node:crypto";
import { normalise } from "@/lib/food/normalise.js";

const CHECK = process.argv.includes("--check");
const OUT = path.resolve(process.cwd(), "src", "lib", "food", "processingData.js");

const BASE = process.env.NEXT_PUBLIC_SUPABASE_URL?.replace(/\/$/, "");
const KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;
if (!BASE || !KEY) {
  console.error("Missing NEXT_PUBLIC_SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY. Run with --env-file=.env.local from web/.");
  process.exit(1);
}

async function readAll(view, select) {
  const rows = [];
  for (let from = 0; ; from += 1000) {
    const res = await fetch(`${BASE}/rest/v1/${view}?select=${select}&order=name`, {
      headers: { apikey: KEY, Authorization: `Bearer ${KEY}`, "Accept-Profile": "food", Range: `${from}-${from + 999}` },
    });
    if (!res.ok) throw new Error(`food.${view} -> ${res.status} ${(await res.text()).slice(0, 200)}`);
    const page = await res.json();
    rows.push(...page);
    if (page.length < 1000) return rows;
  }
}

const RANK = { ultra_processed: 3, processed: 2, culinary: 1, neutral: 0 };
const rows = await readAll("processing_names", "name,role,origin");

const chosen = new Map();
for (const { name, role, origin } of rows) {
  const key = normalise(name);
  if (!key) continue;
  const current = chosen.get(key);
  const better = !current
    || (origin === "term" && current.origin !== "term")
    || (origin === current.origin && RANK[role] > RANK[current.role]);
  if (better) chosen.set(key, { role, origin });
}

const NAMES = [...chosen.entries()].sort((a, b) => a[0].localeCompare(b[0])).map(([name, { role }]) => [name, role]);
const version = createHash("sha256").update(JSON.stringify(NAMES)).digest("hex").slice(0, 12);
const counts = NAMES.reduce((acc, [, role]) => ({ ...acc, [role]: (acc[role] ?? 0) + 1 }), {});

const file = `// ============================================================================
// GENERATED by scripts/buildProcessing.mjs from food.processing_names. Do not
// edit by hand: change food.processing_term or the ingredients, then rebuild.
// ${NAMES.length} names: ${Object.entries(counts).map(([r, n]) => `${n} ${r}`).join(", ")}.
// ============================================================================

export const PROCESSING_VERSION = ${JSON.stringify(version)};

// [normalised name, role: ultra_processed | processed | culinary | neutral]
export const NAMES = ${JSON.stringify(NAMES)};
`;

if (CHECK) {
  const current = fs.existsSync(OUT) ? fs.readFileSync(OUT, "utf8") : "";
  if (current !== file) {
    console.error(`src/lib/food/processingData.js is stale (version ${version}). Rebuild it.`);
    process.exit(1);
  }
  console.log(`The processing names match the database (${version}).`);
} else {
  fs.writeFileSync(OUT, file);
  console.log(`Wrote src/lib/food/processingData.js: ${NAMES.length} names (${JSON.stringify(counts)}), version ${version}.`);
}
