// ============================================================================
// KOI - Compile the active claim rule set into the module claims.js reads
//
// Phase 2.2. The nutrient-claim conditions (FSSAI Schedule I, plus KOI's
// stricter high-protein rule) live in food.claim_rule, grouped under a
// versioned food.claim_rule_set of which exactly one is active. Badges,
// shelves and search decide claims in the browser, so they read a compiled
// copy: src/lib/nutrition/claimRules.js. This writes it; --check fails if it no
// longer matches the database.
//
// Usage, from web/:
//   node --env-file=.env.local scripts/buildClaimRules.mjs          write the file
//   node --env-file=.env.local scripts/buildClaimRules.mjs --check  fail if it is stale
// ============================================================================

import fs from "node:fs";
import path from "node:path";
import { createHash } from "node:crypto";

const CHECK = process.argv.includes("--check");
const OUT = path.resolve(process.cwd(), "src", "lib", "nutrition", "claimRules.js");

const BASE = process.env.NEXT_PUBLIC_SUPABASE_URL?.replace(/\/$/, "");
const KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;
if (!BASE || !KEY) {
  console.error("Missing NEXT_PUBLIC_SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY. Run with --env-file=.env.local from web/.");
  process.exit(1);
}

async function read(query) {
  const res = await fetch(`${BASE}/rest/v1/${query}`, {
    headers: { apikey: KEY, Authorization: `Bearer ${KEY}`, "Accept-Profile": "food" },
  });
  if (!res.ok) throw new Error(`food.${query.split("?")[0]} -> ${res.status} ${(await res.text()).slice(0, 200)}`);
  return res.json();
}

const active = await read("claim_rule_set?select=rule_version&active=eq.true");
if (active.length !== 1) {
  console.error(`Expected exactly one active claim rule set, found ${active.length}.`);
  process.exit(1);
}
const version = active[0].rule_version;
const rows = await read(
  `claim_rule?select=claim_key,clause_group,nutrient,basis,form,comparator,threshold&rule_version=eq.${encodeURIComponent(version)}&order=claim_key,clause_group,nutrient,basis,form`,
);
if (!rows.length) {
  console.error(`The active claim rule set ${version} has no rules.`);
  process.exit(1);
}

const grouped = {};
for (const r of rows) {
  const claim = (grouped[r.claim_key] ??= {});
  (claim[r.clause_group] ??= []).push({
    nutrient: r.nutrient, basis: r.basis, form: r.form, comparator: r.comparator, threshold: Number(r.threshold),
  });
}
const CLAIM_RULES = Object.fromEntries(
  Object.keys(grouped).sort().map((claim) => [
    claim,
    Object.keys(grouped[claim]).map(Number).sort((a, b) => a - b).map((g) => grouped[claim][g]),
  ]),
);
const hash = createHash("sha256").update(JSON.stringify({ version, CLAIM_RULES })).digest("hex").slice(0, 12);

const file = `// ============================================================================
// GENERATED by scripts/buildClaimRules.mjs from the active food.claim_rule_set
// (${version}, ${hash}). Do not edit by hand: change the rules in the database,
// then rebuild.
//
// A claim holds when every clause in any one of its groups holds.
// per_100 is per 100 g for a solid and per 100 ml for a drink.
// ============================================================================

export const CLAIM_RULE_VERSION = ${JSON.stringify(version)};

export const CLAIM_RULES = ${JSON.stringify(CLAIM_RULES, null, 2)};
`;

if (CHECK) {
  const current = fs.existsSync(OUT) ? fs.readFileSync(OUT, "utf8") : "";
  if (current !== file) {
    console.error(`src/lib/nutrition/claimRules.js is stale (${version}, ${hash}). Rebuild it.`);
    process.exit(1);
  }
  console.log(`The claim rules match the database (${version}, ${hash}).`);
} else {
  fs.writeFileSync(OUT, file);
  console.log(`Wrote src/lib/nutrition/claimRules.js: ${rows.length} clauses in ${Object.keys(CLAIM_RULES).length} claims, ${version} (${hash}).`);
}
