// ============================================================================
// Compile the words shoppers use for food into src/lib/food/foodWords.js
//
//   node --experimental-websocket --conditions=react-server \
//        --import ./scripts/testAlias.mjs --env-file=.env.local \
//        scripts/buildFoodWords.mjs
//
// Two questions, one graph:
//
//   WORD_FAMILIES    every other way of writing a food word, from
//                    food.ingredient_alias — so "aata" reaches a product called
//                    "Superior MP Atta" without either word being in the other.
//   CATEGORY_WORDS   the shelf a word means, from food.category_alias — so
//                    "dry fruit" reaches nuts_seeds.dried_fruit.
//
// The same shape as buildAllergenLexicon.mjs and for the same reason: the
// planner runs in the browser's request path and cannot ask the database per
// word, so the graph is compiled in and the file is regenerated when the graph
// moves. A new spelling is a row and a rebuild, never an edit to a reader.
// ============================================================================

import { writeFileSync } from "node:fs";
import { createClient } from "@supabase/supabase-js";

const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
const key = process.env.SUPABASE_SERVICE_ROLE_KEY;
if (!url || !key) {
  console.error("NEXT_PUBLIC_SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY are required.");
  process.exit(1);
}
const db = createClient(url, key, { db: { schema: "food" }, auth: { persistSession: false } });

const { data: ingredients, error: ingredientError } = await db
  .from("ingredients_master")
  .select("id, canonical_name, ingredient_alias(normalised)");
if (ingredientError) throw ingredientError;

const { data: categories, error: categoryError } = await db
  .from("category_alias")
  .select("category_key, normalised");
if (categoryError) throw categoryError;

// A family is the canonical name and every alias of it, each of which maps back
// to the whole family: any one of them, typed, reaches all the others.
const families = new Map();
for (const row of ingredients ?? []) {
  const words = [String(row.canonical_name).toLowerCase(), ...(row.ingredient_alias ?? []).map((a) => a.normalised)]
    .map((w) => String(w).trim())
    .filter((w) => w.length >= 3);
  const family = [...new Set(words)].sort();
  if (family.length < 2) continue;
  for (const word of family) {
    const already = families.get(word) ?? [];
    families.set(word, [...new Set([...already, ...family])].sort());
  }
}

const categoryWords = {};
for (const row of categories ?? []) categoryWords[row.normalised] = row.category_key;

const version = `${families.size}w-${Object.keys(categoryWords).length}c`;
const file = `// GENERATED by scripts/buildFoodWords.mjs — do not edit.
//
// The words shoppers use for food, compiled from food.ingredient_alias and
// food.category_alias (migration 00059). To change one, change the row and run
// the script: this file is the graph's answer, not a second copy of it.

/** Every other way of writing a food word. */
export const WORD_FAMILIES = Object.freeze(${JSON.stringify(Object.fromEntries([...families].sort()), null, 1)});

/** The shelf a word means, when it means a kind of food rather than a product. */
export const CATEGORY_WORDS = Object.freeze(${JSON.stringify(categoryWords, null, 1)});

export const FOOD_WORDS_VERSION = ${JSON.stringify(version)};
`;

writeFileSync("src/lib/food/foodWords.js", file);
console.log(`Wrote src/lib/food/foodWords.js: ${families.size} words in families, ${Object.keys(categoryWords).length} category words, version ${version}.`);
