// ============================================================================
// GENERATED by scripts/buildClaimRules.mjs from the active food.claim_rule_set
// (claims-v1, 53a28ca81270). Do not edit by hand: change the rules in the database,
// then rebuild.
//
// A claim holds when every clause in any one of its groups holds.
// per_100 is per 100 g for a solid and per 100 ml for a drink.
// ============================================================================

export const CLAIM_RULE_VERSION = "claims-v1";

export const CLAIM_RULES = {
  "high_fibre": [
    [
      {
        "nutrient": "fibre_g",
        "basis": "per_100",
        "form": "solid",
        "comparator": "gte",
        "threshold": 6
      }
    ],
    [
      {
        "nutrient": "fibre_g",
        "basis": "per_100kcal",
        "form": "any",
        "comparator": "gte",
        "threshold": 3
      }
    ]
  ],
  "high_protein": [
    [
      {
        "nutrient": "protein_g",
        "basis": "per_100",
        "form": "any",
        "comparator": "gte",
        "threshold": 12
      },
      {
        "nutrient": "protein_g",
        "basis": "per_serving",
        "form": "any",
        "comparator": "gte",
        "threshold": 5
      }
    ]
  ],
  "low_sugar": [
    [
      {
        "nutrient": "sugars_g",
        "basis": "per_100",
        "form": "solid",
        "comparator": "lte",
        "threshold": 5
      }
    ],
    [
      {
        "nutrient": "sugars_g",
        "basis": "per_100",
        "form": "liquid",
        "comparator": "lte",
        "threshold": 2.5
      }
    ]
  ],
  "sugar_free": [
    [
      {
        "nutrient": "sugars_g",
        "basis": "per_100",
        "form": "any",
        "comparator": "lte",
        "threshold": 0.5
      }
    ]
  ]
};
