// GENERATED by scripts/buildDishes.mjs from food.dish + food.recipe_line (00068). Do not edit.
// A dish is a typical home recipe: what it is made of, and where each part comes
// from (a KOI shelf, fresh, or the kitchen). No quantities — amounts come from
// the planner. Allergens and diet flags are derived at runtime (lib/food/dishes.js).

export const DISH_VERSION = "97fbdf4dc8b4";

export const DISHES = Object.freeze([
 {
  "key": "aloo_gobi",
  "name": "Aloo gobi",
  "kind": "main",
  "slots": [
   "lunch",
   "dinner"
  ],
  "cuisine": "indian",
  "prepMinutes": 30,
  "lines": [
   {
    "ingredient": "Potato",
    "supply": "fresh",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Cauliflower",
    "supply": "fresh",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Tomato",
    "supply": "fresh",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Cumin",
    "supply": "kitchen",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Turmeric",
    "supply": "kitchen",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Sunflower Oil",
    "supply": "kitchen",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Iodised Salt",
    "supply": "kitchen",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   }
  ]
 },
 {
  "key": "aloo_paratha",
  "name": "Aloo paratha",
  "kind": "breakfast",
  "slots": [
   "breakfast"
  ],
  "cuisine": "indian",
  "prepMinutes": 35,
  "lines": [
   {
    "ingredient": "Whole Wheat Flour",
    "supply": "shelf",
    "category": "staples.flours",
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Potato",
    "supply": "fresh",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Chilli",
    "supply": "fresh",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Coriander Leaves",
    "supply": "fresh",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Ghee",
    "supply": "shelf",
    "category": "fats_oils.ghee",
    "anyOfShelf": true,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Iodised Salt",
    "supply": "kitchen",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   }
  ]
 },
 {
  "key": "baingan_bharta",
  "name": "Baingan bharta",
  "kind": "main",
  "slots": [
   "lunch",
   "dinner"
  ],
  "cuisine": "indian",
  "prepMinutes": 35,
  "lines": [
   {
    "ingredient": "Brinjal",
    "supply": "fresh",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Onion",
    "supply": "fresh",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Tomato",
    "supply": "fresh",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Garlic",
    "supply": "fresh",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Chilli",
    "supply": "fresh",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Mustard Oil",
    "supply": "kitchen",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Iodised Salt",
    "supply": "kitchen",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   }
  ]
 },
 {
  "key": "besan_chilla",
  "name": "Besan chilla",
  "kind": "breakfast",
  "slots": [
   "breakfast",
   "dinner"
  ],
  "cuisine": "indian",
  "prepMinutes": 20,
  "lines": [
   {
    "ingredient": "Chickpea",
    "supply": "shelf",
    "category": "staples.flours",
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Onion",
    "supply": "fresh",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Tomato",
    "supply": "fresh",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Coriander Leaves",
    "supply": "fresh",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Chilli",
    "supply": "fresh",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Turmeric",
    "supply": "kitchen",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Sunflower Oil",
    "supply": "kitchen",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Iodised Salt",
    "supply": "kitchen",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   }
  ]
 },
 {
  "key": "bhindi_masala",
  "name": "Bhindi masala",
  "kind": "main",
  "slots": [
   "lunch",
   "dinner"
  ],
  "cuisine": "indian",
  "prepMinutes": 25,
  "lines": [
   {
    "ingredient": "Okra",
    "supply": "fresh",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Onion",
    "supply": "fresh",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Turmeric",
    "supply": "kitchen",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Chilli",
    "supply": "fresh",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Sunflower Oil",
    "supply": "kitchen",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Iodised Salt",
    "supply": "kitchen",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   }
  ]
 },
 {
  "key": "chaas",
  "name": "Chaas",
  "kind": "drink",
  "slots": [
   "drinks"
  ],
  "cuisine": "indian",
  "prepMinutes": 5,
  "lines": [
   {
    "ingredient": "Milk",
    "supply": "fresh",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Cumin",
    "supply": "kitchen",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Iodised Salt",
    "supply": "kitchen",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   }
  ]
 },
 {
  "key": "chana_masala",
  "name": "Chana masala",
  "kind": "main",
  "slots": [
   "lunch",
   "dinner"
  ],
  "cuisine": "indian",
  "prepMinutes": 40,
  "lines": [
   {
    "ingredient": "Chickpea",
    "supply": "shelf",
    "category": "staples.pulses",
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Onion",
    "supply": "fresh",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Tomato",
    "supply": "fresh",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Garlic",
    "supply": "fresh",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Ginger",
    "supply": "fresh",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Garam Masala",
    "supply": "kitchen",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": true
   },
   {
    "ingredient": "Sunflower Oil",
    "supply": "kitchen",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Iodised Salt",
    "supply": "kitchen",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   }
  ]
 },
 {
  "key": "chicken_curry",
  "name": "Chicken curry",
  "kind": "main",
  "slots": [
   "lunch",
   "dinner"
  ],
  "cuisine": "indian",
  "prepMinutes": 45,
  "lines": [
   {
    "ingredient": "Chicken",
    "supply": "fresh",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Onion",
    "supply": "fresh",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Tomato",
    "supply": "fresh",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Garlic",
    "supply": "fresh",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Ginger",
    "supply": "fresh",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Garam Masala",
    "supply": "kitchen",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": true
   },
   {
    "ingredient": "Sunflower Oil",
    "supply": "kitchen",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Iodised Salt",
    "supply": "kitchen",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   }
  ]
 },
 {
  "key": "curd_rice",
  "name": "Curd rice",
  "kind": "one_pot",
  "slots": [
   "lunch",
   "dinner"
  ],
  "cuisine": "indian",
  "prepMinutes": 15,
  "lines": [
   {
    "ingredient": "Polished Rice",
    "supply": "shelf",
    "category": "staples.rice",
    "anyOfShelf": true,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Milk",
    "supply": "fresh",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Mustard",
    "supply": "kitchen",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Curry Leaves",
    "supply": "fresh",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Iodised Salt",
    "supply": "kitchen",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   }
  ]
 },
 {
  "key": "dal_tadka",
  "name": "Dal tadka",
  "kind": "main",
  "slots": [
   "lunch",
   "dinner"
  ],
  "cuisine": "indian",
  "prepMinutes": 35,
  "lines": [
   {
    "ingredient": "Lentils",
    "supply": "shelf",
    "category": "staples.pulses",
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Ghee",
    "supply": "shelf",
    "category": "fats_oils.ghee",
    "anyOfShelf": true,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Cumin",
    "supply": "kitchen",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Garlic",
    "supply": "fresh",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Onion",
    "supply": "fresh",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Tomato",
    "supply": "fresh",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Turmeric",
    "supply": "kitchen",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Chilli",
    "supply": "fresh",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Asafoetida",
    "supply": "kitchen",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": true
   },
   {
    "ingredient": "Iodised Salt",
    "supply": "kitchen",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   }
  ]
 },
 {
  "key": "dates_and_nuts",
  "name": "Dates with nuts",
  "kind": "snack",
  "slots": [
   "snack"
  ],
  "cuisine": null,
  "prepMinutes": 1,
  "lines": [
   {
    "ingredient": "Dates",
    "supply": "shelf",
    "category": "nuts_seeds.dried_fruit",
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Tree Nuts",
    "supply": "shelf",
    "category": "nuts_seeds.nuts",
    "anyOfShelf": true,
    "optional": false,
    "blend": false
   }
  ]
 },
 {
  "key": "egg_bhurji",
  "name": "Egg bhurji",
  "kind": "breakfast",
  "slots": [
   "breakfast",
   "dinner"
  ],
  "cuisine": "indian",
  "prepMinutes": 15,
  "lines": [
   {
    "ingredient": "Egg",
    "supply": "fresh",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Onion",
    "supply": "fresh",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Tomato",
    "supply": "fresh",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Chilli",
    "supply": "fresh",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Turmeric",
    "supply": "kitchen",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Sunflower Oil",
    "supply": "kitchen",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Iodised Salt",
    "supply": "kitchen",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   }
  ]
 },
 {
  "key": "egg_curry",
  "name": "Egg curry",
  "kind": "main",
  "slots": [
   "lunch",
   "dinner"
  ],
  "cuisine": "indian",
  "prepMinutes": 30,
  "lines": [
   {
    "ingredient": "Egg",
    "supply": "fresh",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Onion",
    "supply": "fresh",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Tomato",
    "supply": "fresh",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Garlic",
    "supply": "fresh",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Ginger",
    "supply": "fresh",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Garam Masala",
    "supply": "kitchen",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": true
   },
   {
    "ingredient": "Sunflower Oil",
    "supply": "kitchen",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Iodised Salt",
    "supply": "kitchen",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   }
  ]
 },
 {
  "key": "filter_coffee",
  "name": "Filter coffee",
  "kind": "drink",
  "slots": [
   "drinks"
  ],
  "cuisine": "indian",
  "prepMinutes": 10,
  "lines": [
   {
    "ingredient": "Coffee",
    "supply": "shelf",
    "category": "beverages.tea_coffee",
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Milk",
    "supply": "fresh",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Refined Sugar",
    "supply": "shelf",
    "category": "sweeteners.sugar",
    "anyOfShelf": true,
    "optional": true,
    "blend": false
   }
  ]
 },
 {
  "key": "fish_curry",
  "name": "Fish curry",
  "kind": "main",
  "slots": [
   "lunch",
   "dinner"
  ],
  "cuisine": "indian",
  "prepMinutes": 35,
  "lines": [
   {
    "ingredient": "Fish",
    "supply": "fresh",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Onion",
    "supply": "fresh",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Tomato",
    "supply": "fresh",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Garlic",
    "supply": "fresh",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Turmeric",
    "supply": "kitchen",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Chilli",
    "supply": "fresh",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Mustard Oil",
    "supply": "kitchen",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Iodised Salt",
    "supply": "kitchen",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   }
  ]
 },
 {
  "key": "fruit_bowl",
  "name": "Fruit bowl",
  "kind": "snack",
  "slots": [
   "snack",
   "breakfast"
  ],
  "cuisine": null,
  "prepMinutes": 5,
  "lines": [
   {
    "ingredient": "Banana",
    "supply": "fresh",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Apple",
    "supply": "fresh",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   }
  ]
 },
 {
  "key": "haldi_doodh",
  "name": "Haldi doodh",
  "kind": "drink",
  "slots": [
   "drinks"
  ],
  "cuisine": "indian",
  "prepMinutes": 10,
  "lines": [
   {
    "ingredient": "Milk",
    "supply": "fresh",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Turmeric",
    "supply": "kitchen",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Jaggery",
    "supply": "shelf",
    "category": "sweeteners.jaggery",
    "anyOfShelf": true,
    "optional": true,
    "blend": false
   }
  ]
 },
 {
  "key": "handful_nuts",
  "name": "A handful of nuts",
  "kind": "snack",
  "slots": [
   "snack"
  ],
  "cuisine": null,
  "prepMinutes": 1,
  "lines": [
   {
    "ingredient": "Tree Nuts",
    "supply": "shelf",
    "category": "nuts_seeds.nuts",
    "anyOfShelf": true,
    "optional": false,
    "blend": false
   }
  ]
 },
 {
  "key": "jain_moong_dal",
  "name": "Moong dal (no onion-garlic)",
  "kind": "main",
  "slots": [
   "lunch",
   "dinner"
  ],
  "cuisine": "indian",
  "prepMinutes": 30,
  "lines": [
   {
    "ingredient": "Lentils",
    "supply": "shelf",
    "category": "staples.pulses",
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Ghee",
    "supply": "shelf",
    "category": "fats_oils.ghee",
    "anyOfShelf": true,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Cumin",
    "supply": "kitchen",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Tomato",
    "supply": "fresh",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Turmeric",
    "supply": "kitchen",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Iodised Salt",
    "supply": "kitchen",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   }
  ]
 },
 {
  "key": "jeera_rice",
  "name": "Jeera rice",
  "kind": "base",
  "slots": [
   "lunch",
   "dinner"
  ],
  "cuisine": "indian",
  "prepMinutes": 25,
  "lines": [
   {
    "ingredient": "Polished Rice",
    "supply": "shelf",
    "category": "staples.rice",
    "anyOfShelf": true,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Cumin",
    "supply": "kitchen",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Ghee",
    "supply": "shelf",
    "category": "fats_oils.ghee",
    "anyOfShelf": true,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Iodised Salt",
    "supply": "kitchen",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   }
  ]
 },
 {
  "key": "kanda_poha",
  "name": "Kanda poha",
  "kind": "breakfast",
  "slots": [
   "breakfast"
  ],
  "cuisine": "indian",
  "prepMinutes": 20,
  "lines": [
   {
    "ingredient": "Flattened Rice",
    "supply": "shelf",
    "category": "staples.breakfast_cereals",
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Onion",
    "supply": "fresh",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Mustard",
    "supply": "kitchen",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Turmeric",
    "supply": "kitchen",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Curry Leaves",
    "supply": "fresh",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Chilli",
    "supply": "fresh",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Peanut",
    "supply": "kitchen",
    "category": null,
    "anyOfShelf": false,
    "optional": true,
    "blend": false
   },
   {
    "ingredient": "Lemon",
    "supply": "fresh",
    "category": null,
    "anyOfShelf": false,
    "optional": true,
    "blend": false
   },
   {
    "ingredient": "Sunflower Oil",
    "supply": "kitchen",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Iodised Salt",
    "supply": "kitchen",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   }
  ]
 },
 {
  "key": "lauki_sabzi",
  "name": "Lauki sabzi",
  "kind": "main",
  "slots": [
   "lunch",
   "dinner"
  ],
  "cuisine": "indian",
  "prepMinutes": 25,
  "lines": [
   {
    "ingredient": "Bottle Gourd",
    "supply": "fresh",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Tomato",
    "supply": "fresh",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Cumin",
    "supply": "kitchen",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Turmeric",
    "supply": "kitchen",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Sunflower Oil",
    "supply": "kitchen",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Iodised Salt",
    "supply": "kitchen",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   }
  ]
 },
 {
  "key": "masala_chai",
  "name": "Masala chai",
  "kind": "drink",
  "slots": [
   "drinks"
  ],
  "cuisine": "indian",
  "prepMinutes": 10,
  "lines": [
   {
    "ingredient": "Tea",
    "supply": "shelf",
    "category": "beverages.tea_coffee",
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Milk",
    "supply": "fresh",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Ginger",
    "supply": "fresh",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Refined Sugar",
    "supply": "shelf",
    "category": "sweeteners.sugar",
    "anyOfShelf": true,
    "optional": true,
    "blend": false
   }
  ]
 },
 {
  "key": "masala_omelette",
  "name": "Masala omelette",
  "kind": "breakfast",
  "slots": [
   "breakfast"
  ],
  "cuisine": "indian",
  "prepMinutes": 10,
  "lines": [
   {
    "ingredient": "Egg",
    "supply": "fresh",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Onion",
    "supply": "fresh",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Chilli",
    "supply": "fresh",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Sunflower Oil",
    "supply": "kitchen",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Iodised Salt",
    "supply": "kitchen",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   }
  ]
 },
 {
  "key": "millet_roti",
  "name": "Millet roti",
  "kind": "base",
  "slots": [
   "lunch",
   "dinner"
  ],
  "cuisine": "indian",
  "prepMinutes": 25,
  "lines": [
   {
    "ingredient": "Jowar",
    "supply": "shelf",
    "category": "staples.millets",
    "anyOfShelf": true,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Iodised Salt",
    "supply": "kitchen",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   }
  ]
 },
 {
  "key": "mixed_veg",
  "name": "Mixed vegetable sabzi",
  "kind": "main",
  "slots": [
   "lunch",
   "dinner"
  ],
  "cuisine": "indian",
  "prepMinutes": 30,
  "lines": [
   {
    "ingredient": "Potato",
    "supply": "fresh",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Cauliflower",
    "supply": "fresh",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Green Peas",
    "supply": "fresh",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Carrot",
    "supply": "fresh",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Onion",
    "supply": "fresh",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Tomato",
    "supply": "fresh",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Turmeric",
    "supply": "kitchen",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Sunflower Oil",
    "supply": "kitchen",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Iodised Salt",
    "supply": "kitchen",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   }
  ]
 },
 {
  "key": "moong_chilla",
  "name": "Moong dal chilla",
  "kind": "breakfast",
  "slots": [
   "breakfast"
  ],
  "cuisine": "indian",
  "prepMinutes": 25,
  "lines": [
   {
    "ingredient": "Lentils",
    "supply": "shelf",
    "category": "staples.pulses",
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Ginger",
    "supply": "fresh",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Chilli",
    "supply": "fresh",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Coriander Leaves",
    "supply": "fresh",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Sunflower Oil",
    "supply": "kitchen",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Iodised Salt",
    "supply": "kitchen",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   }
  ]
 },
 {
  "key": "moong_khichdi",
  "name": "Moong dal khichdi",
  "kind": "one_pot",
  "slots": [
   "lunch",
   "dinner"
  ],
  "cuisine": "indian",
  "prepMinutes": 30,
  "lines": [
   {
    "ingredient": "Polished Rice",
    "supply": "shelf",
    "category": "staples.rice",
    "anyOfShelf": true,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Lentils",
    "supply": "shelf",
    "category": "staples.pulses",
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Ghee",
    "supply": "shelf",
    "category": "fats_oils.ghee",
    "anyOfShelf": true,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Cumin",
    "supply": "kitchen",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Turmeric",
    "supply": "kitchen",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Iodised Salt",
    "supply": "kitchen",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   }
  ]
 },
 {
  "key": "muesli_curd",
  "name": "Muesli with curd",
  "kind": "breakfast",
  "slots": [
   "breakfast"
  ],
  "cuisine": "global",
  "prepMinutes": 5,
  "lines": [
   {
    "ingredient": "Oats",
    "supply": "shelf",
    "category": "staples.breakfast_cereals",
    "anyOfShelf": true,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Milk",
    "supply": "fresh",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Banana",
    "supply": "fresh",
    "category": null,
    "anyOfShelf": false,
    "optional": true,
    "blend": false
   }
  ]
 },
 {
  "key": "nimbu_pani",
  "name": "Nimbu pani",
  "kind": "drink",
  "slots": [
   "drinks"
  ],
  "cuisine": "indian",
  "prepMinutes": 5,
  "lines": [
   {
    "ingredient": "Lemon",
    "supply": "fresh",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Refined Sugar",
    "supply": "shelf",
    "category": "sweeteners.sugar",
    "anyOfShelf": true,
    "optional": true,
    "blend": false
   },
   {
    "ingredient": "Iodised Salt",
    "supply": "kitchen",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   }
  ]
 },
 {
  "key": "oats_porridge",
  "name": "Oats porridge",
  "kind": "breakfast",
  "slots": [
   "breakfast"
  ],
  "cuisine": "global",
  "prepMinutes": 10,
  "lines": [
   {
    "ingredient": "Oats",
    "supply": "shelf",
    "category": "staples.breakfast_cereals",
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Milk",
    "supply": "fresh",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Banana",
    "supply": "fresh",
    "category": null,
    "anyOfShelf": false,
    "optional": true,
    "blend": false
   },
   {
    "ingredient": "Honey",
    "supply": "shelf",
    "category": "sweeteners.honey",
    "anyOfShelf": true,
    "optional": true,
    "blend": false
   }
  ]
 },
 {
  "key": "palak_paneer",
  "name": "Palak paneer",
  "kind": "main",
  "slots": [
   "lunch",
   "dinner"
  ],
  "cuisine": "indian",
  "prepMinutes": 35,
  "lines": [
   {
    "ingredient": "Spinach",
    "supply": "fresh",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Milk",
    "supply": "fresh",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Onion",
    "supply": "fresh",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Garlic",
    "supply": "fresh",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Ginger",
    "supply": "fresh",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Garam Masala",
    "supply": "kitchen",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": true
   },
   {
    "ingredient": "Sunflower Oil",
    "supply": "kitchen",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Iodised Salt",
    "supply": "kitchen",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   }
  ]
 },
 {
  "key": "paneer_bhurji",
  "name": "Paneer bhurji",
  "kind": "main",
  "slots": [
   "lunch",
   "dinner"
  ],
  "cuisine": "indian",
  "prepMinutes": 20,
  "lines": [
   {
    "ingredient": "Milk",
    "supply": "fresh",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Onion",
    "supply": "fresh",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Tomato",
    "supply": "fresh",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Chilli",
    "supply": "fresh",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Turmeric",
    "supply": "kitchen",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Sunflower Oil",
    "supply": "kitchen",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Iodised Salt",
    "supply": "kitchen",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   }
  ]
 },
 {
  "key": "phulka",
  "name": "Phulka",
  "kind": "base",
  "slots": [
   "lunch",
   "dinner"
  ],
  "cuisine": "indian",
  "prepMinutes": 20,
  "lines": [
   {
    "ingredient": "Whole Wheat Flour",
    "supply": "shelf",
    "category": "staples.flours",
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   }
  ]
 },
 {
  "key": "ragi_porridge",
  "name": "Ragi porridge",
  "kind": "breakfast",
  "slots": [
   "breakfast"
  ],
  "cuisine": "indian",
  "prepMinutes": 15,
  "lines": [
   {
    "ingredient": "Ragi",
    "supply": "shelf",
    "category": "staples.millets",
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Milk",
    "supply": "fresh",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Jaggery",
    "supply": "shelf",
    "category": "sweeteners.jaggery",
    "anyOfShelf": true,
    "optional": true,
    "blend": false
   }
  ]
 },
 {
  "key": "rajma",
  "name": "Rajma",
  "kind": "main",
  "slots": [
   "lunch",
   "dinner"
  ],
  "cuisine": "indian",
  "prepMinutes": 45,
  "lines": [
   {
    "ingredient": "Kidney Beans",
    "supply": "shelf",
    "category": "staples.pulses",
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Onion",
    "supply": "fresh",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Tomato",
    "supply": "fresh",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Garlic",
    "supply": "fresh",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Ginger",
    "supply": "fresh",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Garam Masala",
    "supply": "kitchen",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": true
   },
   {
    "ingredient": "Sunflower Oil",
    "supply": "kitchen",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Iodised Salt",
    "supply": "kitchen",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   }
  ]
 },
 {
  "key": "rava_upma",
  "name": "Rava upma",
  "kind": "breakfast",
  "slots": [
   "breakfast"
  ],
  "cuisine": "indian",
  "prepMinutes": 20,
  "lines": [
   {
    "ingredient": "Wheat",
    "supply": "shelf",
    "category": "staples.flours",
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Onion",
    "supply": "fresh",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Mustard",
    "supply": "kitchen",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Curry Leaves",
    "supply": "fresh",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Ginger",
    "supply": "fresh",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Chilli",
    "supply": "fresh",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Sunflower Oil",
    "supply": "kitchen",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Iodised Salt",
    "supply": "kitchen",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   }
  ]
 },
 {
  "key": "roasted_chana",
  "name": "Roasted chana",
  "kind": "snack",
  "slots": [
   "snack"
  ],
  "cuisine": "indian",
  "prepMinutes": 1,
  "lines": [
   {
    "ingredient": "Chickpea",
    "supply": "shelf",
    "category": "staples.pulses",
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   }
  ]
 },
 {
  "key": "roasted_makhana",
  "name": "Roasted makhana",
  "kind": "snack",
  "slots": [
   "snack"
  ],
  "cuisine": "indian",
  "prepMinutes": 10,
  "lines": [
   {
    "ingredient": "Makhana",
    "supply": "shelf",
    "category": "snacks.puffs",
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Ghee",
    "supply": "shelf",
    "category": "fats_oils.ghee",
    "anyOfShelf": true,
    "optional": true,
    "blend": false
   }
  ]
 },
 {
  "key": "soya_curry",
  "name": "Soya chunk curry",
  "kind": "main",
  "slots": [
   "lunch",
   "dinner"
  ],
  "cuisine": "indian",
  "prepMinutes": 30,
  "lines": [
   {
    "ingredient": "Soya",
    "supply": "shelf",
    "category": "staples.pulses",
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Onion",
    "supply": "fresh",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Tomato",
    "supply": "fresh",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Garlic",
    "supply": "fresh",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Ginger",
    "supply": "fresh",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Garam Masala",
    "supply": "kitchen",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": true
   },
   {
    "ingredient": "Sunflower Oil",
    "supply": "kitchen",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Iodised Salt",
    "supply": "kitchen",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   }
  ]
 },
 {
  "key": "sprouts_chaat",
  "name": "Moong sprouts chaat",
  "kind": "breakfast",
  "slots": [
   "breakfast",
   "snack"
  ],
  "cuisine": "indian",
  "prepMinutes": 10,
  "lines": [
   {
    "ingredient": "Lentils",
    "supply": "shelf",
    "category": "staples.pulses",
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Onion",
    "supply": "fresh",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Tomato",
    "supply": "fresh",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Lemon",
    "supply": "fresh",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Chilli",
    "supply": "fresh",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Iodised Salt",
    "supply": "kitchen",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   }
  ]
 },
 {
  "key": "steamed_rice",
  "name": "Steamed rice",
  "kind": "base",
  "slots": [
   "lunch",
   "dinner"
  ],
  "cuisine": null,
  "prepMinutes": 20,
  "lines": [
   {
    "ingredient": "Polished Rice",
    "supply": "shelf",
    "category": "staples.rice",
    "anyOfShelf": true,
    "optional": false,
    "blend": false
   }
  ]
 },
 {
  "key": "veg_pulao",
  "name": "Vegetable pulao",
  "kind": "one_pot",
  "slots": [
   "lunch",
   "dinner"
  ],
  "cuisine": "indian",
  "prepMinutes": 35,
  "lines": [
   {
    "ingredient": "Polished Rice",
    "supply": "shelf",
    "category": "staples.rice",
    "anyOfShelf": true,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Green Peas",
    "supply": "fresh",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Carrot",
    "supply": "fresh",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Onion",
    "supply": "fresh",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Garam Masala",
    "supply": "kitchen",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": true
   },
   {
    "ingredient": "Ghee",
    "supply": "shelf",
    "category": "fats_oils.ghee",
    "anyOfShelf": true,
    "optional": false,
    "blend": false
   },
   {
    "ingredient": "Iodised Salt",
    "supply": "kitchen",
    "category": null,
    "anyOfShelf": false,
    "optional": false,
    "blend": false
   }
  ]
 }
]);
