// GENERATED by scripts/buildFoodWords.mjs — do not edit.
//
// The words shoppers use for food, compiled from food.ingredient_alias and
// food.category_alias (migration 00059). To change one, change the row and run
// the script: this file is the graph's answer, not a second copy of it.

/** Every other way of writing a food word. */
export const WORD_FAMILIES = Object.freeze({
 "aata": [
  "aata",
  "aatta",
  "ata",
  "atta",
  "chakki atta",
  "gehun atta",
  "whole meal flour",
  "whole wheat flour",
  "wholewheat flour"
 ],
 "aatta": [
  "aata",
  "aatta",
  "ata",
  "atta",
  "chakki atta",
  "gehun atta",
  "whole meal flour",
  "whole wheat flour",
  "wholewheat flour"
 ],
 "acacia gum": [
  "acacia gum",
  "e414",
  "gum arabic",
  "ins 414"
 ],
 "ace k": [
  "ace k",
  "acesulfame k",
  "acesulfame potassium",
  "e950",
  "ins 950"
 ],
 "acesulfame k": [
  "ace k",
  "acesulfame k",
  "acesulfame potassium",
  "e950",
  "ins 950"
 ],
 "acesulfame potassium": [
  "ace k",
  "acesulfame k",
  "acesulfame potassium",
  "e950",
  "ins 950"
 ],
 "acetic acid": [
  "acetic acid",
  "e260",
  "ins 260",
  "vinegar"
 ],
 "acetylated distarch adipate": [
  "acetylated distarch adipate",
  "e1422",
  "ins 1422",
  "modified corn starch",
  "modified starch"
 ],
 "adrak": [
  "adrak",
  "dry ginger",
  "ginger",
  "ginger powder",
  "sonth"
 ],
 "ajinomoto": [
  "ajinomoto",
  "e621",
  "flavour enhancer 621",
  "ins 621",
  "monosodium glutamate",
  "msg",
  "taste maker"
 ],
 "akhrot": [
  "akhrot",
  "almond",
  "almond butter",
  "almond milk",
  "badam",
  "brazil nut",
  "cashew",
  "cashew butter",
  "cashew nut",
  "chilgoza",
  "dry fruit",
  "dry fruits",
  "dryfruit",
  "dryfruits",
  "hazelnut",
  "kaju",
  "macadamia",
  "marzipan",
  "pecan",
  "pine nut",
  "pista",
  "pistachio",
  "tree nuts",
  "walnut"
 ],
 "albumen": [
  "albumen",
  "albumin",
  "anda",
  "egg",
  "egg powder",
  "egg white",
  "egg yolk",
  "liquid egg"
 ],
 "albumin": [
  "albumen",
  "albumin",
  "anda",
  "egg",
  "egg powder",
  "egg white",
  "egg yolk",
  "liquid egg"
 ],
 "all purpose flour": [
  "all purpose flour",
  "apf",
  "maida",
  "refined flour",
  "refined wheat flour",
  "white flour"
 ],
 "allura red ac": [
  "allura red",
  "allura red ac",
  "e129",
  "fd c red 40",
  "ins 129",
  "red 40"
 ],
 "allura red": [
  "allura red",
  "allura red ac",
  "e129",
  "fd c red 40",
  "ins 129",
  "red 40"
 ],
 "almond butter": [
  "akhrot",
  "almond",
  "almond butter",
  "almond milk",
  "badam",
  "brazil nut",
  "cashew",
  "cashew butter",
  "cashew nut",
  "chilgoza",
  "dry fruit",
  "dry fruits",
  "dryfruit",
  "dryfruits",
  "hazelnut",
  "kaju",
  "macadamia",
  "marzipan",
  "pecan",
  "pine nut",
  "pista",
  "pistachio",
  "tree nuts",
  "walnut"
 ],
 "almond milk": [
  "akhrot",
  "almond",
  "almond butter",
  "almond milk",
  "badam",
  "brazil nut",
  "cashew",
  "cashew butter",
  "cashew nut",
  "chilgoza",
  "dry fruit",
  "dry fruits",
  "dryfruit",
  "dryfruits",
  "hazelnut",
  "kaju",
  "macadamia",
  "marzipan",
  "pecan",
  "pine nut",
  "pista",
  "pistachio",
  "tree nuts",
  "walnut"
 ],
 "almond": [
  "akhrot",
  "almond",
  "almond butter",
  "almond milk",
  "badam",
  "brazil nut",
  "cashew",
  "cashew butter",
  "cashew nut",
  "chilgoza",
  "dry fruit",
  "dry fruits",
  "dryfruit",
  "dryfruits",
  "hazelnut",
  "kaju",
  "macadamia",
  "marzipan",
  "pecan",
  "pine nut",
  "pista",
  "pistachio",
  "tree nuts",
  "walnut"
 ],
 "aloo": [
  "aloo",
  "dehydrated potato",
  "potato",
  "potato flakes",
  "potato powder"
 ],
 "alsi": [
  "alsi",
  "flax seeds",
  "flaxseed",
  "linseed"
 ],
 "amaranth": [
  "amaranth",
  "rajgira",
  "ramdana"
 ],
 "anchovy": [
  "anchovy",
  "fish",
  "fish oil",
  "fish sauce",
  "machhli",
  "machli",
  "salmon",
  "sardine",
  "tuna"
 ],
 "anda": [
  "albumen",
  "albumin",
  "anda",
  "egg",
  "egg powder",
  "egg white",
  "egg yolk",
  "liquid egg"
 ],
 "annatto": [
  "annatto",
  "bixin",
  "e160b",
  "ins 160b",
  "norbixin"
 ],
 "anthocyanin": [
  "anthocyanin",
  "anthocyanins",
  "e163",
  "grape skin extract",
  "ins 163"
 ],
 "anthocyanins": [
  "anthocyanin",
  "anthocyanins",
  "e163",
  "grape skin extract",
  "ins 163"
 ],
 "apf": [
  "all purpose flour",
  "apf",
  "maida",
  "refined flour",
  "refined wheat flour",
  "white flour"
 ],
 "arachis oil": [
  "arachis oil",
  "groundnut oil",
  "peanut oil"
 ],
 "arbi": [
  "arbi",
  "colocasia",
  "taro"
 ],
 "arhar": [
  "arhar",
  "daal",
  "dal",
  "dhal",
  "lentil",
  "lentils",
  "masoor",
  "moong",
  "pulse",
  "toor",
  "urad"
 ],
 "artificial flavor": [
  "artificial flavor",
  "artificial flavoring",
  "artificial flavoring substances",
  "artificial flavors",
  "artificial flavour",
  "artificial flavouring",
  "artificial flavouring substances",
  "artificial flavours"
 ],
 "artificial flavoring substances": [
  "artificial flavor",
  "artificial flavoring",
  "artificial flavoring substances",
  "artificial flavors",
  "artificial flavour",
  "artificial flavouring",
  "artificial flavouring substances",
  "artificial flavours"
 ],
 "artificial flavoring": [
  "artificial flavor",
  "artificial flavoring",
  "artificial flavoring substances",
  "artificial flavors",
  "artificial flavour",
  "artificial flavouring",
  "artificial flavouring substances",
  "artificial flavours"
 ],
 "artificial flavors": [
  "artificial flavor",
  "artificial flavoring",
  "artificial flavoring substances",
  "artificial flavors",
  "artificial flavour",
  "artificial flavouring",
  "artificial flavouring substances",
  "artificial flavours"
 ],
 "artificial flavour": [
  "artificial flavor",
  "artificial flavoring",
  "artificial flavoring substances",
  "artificial flavors",
  "artificial flavour",
  "artificial flavouring",
  "artificial flavouring substances",
  "artificial flavours"
 ],
 "artificial flavouring substances": [
  "artificial flavor",
  "artificial flavoring",
  "artificial flavoring substances",
  "artificial flavors",
  "artificial flavour",
  "artificial flavouring",
  "artificial flavouring substances",
  "artificial flavours"
 ],
 "artificial flavouring": [
  "artificial flavor",
  "artificial flavoring",
  "artificial flavoring substances",
  "artificial flavors",
  "artificial flavour",
  "artificial flavouring",
  "artificial flavouring substances",
  "artificial flavours"
 ],
 "artificial flavours": [
  "artificial flavor",
  "artificial flavoring",
  "artificial flavoring substances",
  "artificial flavors",
  "artificial flavour",
  "artificial flavouring",
  "artificial flavouring substances",
  "artificial flavours"
 ],
 "ascorbic acid": [
  "ascorbic acid",
  "e300",
  "ins 300",
  "vitamin c"
 ],
 "aspartame": [
  "aspartame",
  "e951",
  "ins 951"
 ],
 "ata": [
  "aata",
  "aatta",
  "ata",
  "atta",
  "chakki atta",
  "gehun atta",
  "whole meal flour",
  "whole wheat flour",
  "wholewheat flour"
 ],
 "atta": [
  "aata",
  "aatta",
  "ata",
  "atta",
  "chakki atta",
  "gehun atta",
  "whole meal flour",
  "whole wheat flour",
  "wholewheat flour"
 ],
 "autolysed yeast": [
  "autolysed yeast",
  "hvp",
  "hydrolysed vegetable protein",
  "yeast extract"
 ],
 "azorubine": [
  "azorubine",
  "carmoisine",
  "e122",
  "ins 122"
 ],
 "bacon": [
  "bacon",
  "ham",
  "pork"
 ],
 "badam": [
  "akhrot",
  "almond",
  "almond butter",
  "almond milk",
  "badam",
  "brazil nut",
  "cashew",
  "cashew butter",
  "cashew nut",
  "chilgoza",
  "dry fruit",
  "dry fruits",
  "dryfruit",
  "dryfruits",
  "hazelnut",
  "kaju",
  "macadamia",
  "marzipan",
  "pecan",
  "pine nut",
  "pista",
  "pistachio",
  "tree nuts",
  "walnut"
 ],
 "bajra flour": [
  "bajra",
  "bajra flour",
  "pearl millet"
 ],
 "bajra": [
  "bajra",
  "bajra flour",
  "pearl millet"
 ],
 "baking soda": [
  "baking soda",
  "e500",
  "ins 500",
  "sodium bicarbonate"
 ],
 "barley": [
  "barley",
  "jau",
  "pearl barley"
 ],
 "basmati rice": [
  "basmati rice",
  "chaval",
  "chawal",
  "polished rice",
  "white rice"
 ],
 "beetroot red": [
  "beetroot red",
  "betanin",
  "e162",
  "ins 162"
 ],
 "beetroot": [
  "beetroot",
  "chukandar"
 ],
 "benzoate": [
  "benzoate",
  "e211",
  "ins 211",
  "sodium benzoate"
 ],
 "benzoic acid": [
  "benzoic acid",
  "e210",
  "ins 210"
 ],
 "besan": [
  "besan",
  "chana",
  "chana dal",
  "chickpea",
  "gram flour",
  "kabuli chana"
 ],
 "beta carotene": [
  "beta carotene",
  "beta-carotene",
  "carotene",
  "e160a",
  "ins 160a"
 ],
 "beta-carotene": [
  "beta carotene",
  "beta-carotene",
  "carotene",
  "e160a",
  "ins 160a"
 ],
 "betanin": [
  "beetroot red",
  "betanin",
  "e162",
  "ins 162"
 ],
 "bha": [
  "bha",
  "butylated hydroxyanisole",
  "e320",
  "ins 320"
 ],
 "bht": [
  "bht",
  "butylated hydroxytoluene",
  "e321",
  "ins 321"
 ],
 "bifidobacterium": [
  "bifidobacterium",
  "dahi culture",
  "lactobacillus",
  "live cultures",
  "probiotic cultures",
  "yoghurt culture",
  "yoghurt cultures"
 ],
 "binola oil": [
  "binola oil",
  "cottonseed oil"
 ],
 "bixin": [
  "annatto",
  "bixin",
  "e160b",
  "ins 160b",
  "norbixin"
 ],
 "black tea": [
  "black tea",
  "green tea",
  "green tea extract",
  "tea",
  "tea extract",
  "tea leaves",
  "tea powder"
 ],
 "brazil nut": [
  "akhrot",
  "almond",
  "almond butter",
  "almond milk",
  "badam",
  "brazil nut",
  "cashew",
  "cashew butter",
  "cashew nut",
  "chilgoza",
  "dry fruit",
  "dry fruits",
  "dryfruit",
  "dryfruits",
  "hazelnut",
  "kaju",
  "macadamia",
  "marzipan",
  "pecan",
  "pine nut",
  "pista",
  "pistachio",
  "tree nuts",
  "walnut"
 ],
 "bread crumbs": [
  "bread",
  "bread crumbs",
  "breadcrumbs",
  "couscous",
  "durum",
  "pasta",
  "rava",
  "semolina",
  "suji",
  "wheat",
  "wheat flour",
  "whole wheat",
  "wholewheat"
 ],
 "bread": [
  "bread",
  "bread crumbs",
  "breadcrumbs",
  "couscous",
  "durum",
  "pasta",
  "rava",
  "semolina",
  "suji",
  "wheat",
  "wheat flour",
  "whole wheat",
  "wholewheat"
 ],
 "breadcrumbs": [
  "bread",
  "bread crumbs",
  "breadcrumbs",
  "couscous",
  "durum",
  "pasta",
  "rava",
  "semolina",
  "suji",
  "wheat",
  "wheat flour",
  "whole wheat",
  "wholewheat"
 ],
 "brilliant blue fcf": [
  "brilliant blue",
  "brilliant blue fcf",
  "e133",
  "fd c blue 1",
  "ins 133"
 ],
 "brilliant blue": [
  "brilliant blue",
  "brilliant blue fcf",
  "e133",
  "fd c blue 1",
  "ins 133"
 ],
 "bromate": [
  "bromate",
  "e924",
  "ins 924",
  "potassium bromate"
 ],
 "brominated vegetable oil": [
  "brominated vegetable oil",
  "bvo"
 ],
 "brown rice": [
  "brown rice",
  "unpolished rice"
 ],
 "buckwheat": [
  "buckwheat",
  "kuttu",
  "kuttu atta"
 ],
 "butter": [
  "butter",
  "buttermilk",
  "chaas",
  "cheese",
  "chhena",
  "cream",
  "curd",
  "dahi",
  "dairy",
  "khoya",
  "lactose",
  "makhan",
  "malai",
  "mawa",
  "milk",
  "milk fat",
  "milk powder",
  "milk solids",
  "milkfat",
  "paneer",
  "skimmed milk powder",
  "smp",
  "yoghurt",
  "yogurt"
 ],
 "buttermilk": [
  "butter",
  "buttermilk",
  "chaas",
  "cheese",
  "chhena",
  "cream",
  "curd",
  "dahi",
  "dairy",
  "khoya",
  "lactose",
  "makhan",
  "malai",
  "mawa",
  "milk",
  "milk fat",
  "milk powder",
  "milk solids",
  "milkfat",
  "paneer",
  "skimmed milk powder",
  "smp",
  "yoghurt",
  "yogurt"
 ],
 "butylated hydroxyanisole": [
  "bha",
  "butylated hydroxyanisole",
  "e320",
  "ins 320"
 ],
 "butylated hydroxytoluene": [
  "bht",
  "butylated hydroxytoluene",
  "e321",
  "ins 321"
 ],
 "bvo": [
  "brominated vegetable oil",
  "bvo"
 ],
 "cacao": [
  "cacao",
  "cocoa",
  "cocoa mass",
  "cocoa powder",
  "cocoa solids"
 ],
 "caffeine anhydrous": [
  "caffeine",
  "caffeine anhydrous",
  "caffeine powder"
 ],
 "caffeine powder": [
  "caffeine",
  "caffeine anhydrous",
  "caffeine powder"
 ],
 "caffeine": [
  "caffeine",
  "caffeine anhydrous",
  "caffeine powder"
 ],
 "calcium carbonate": [
  "calcium carbonate",
  "chalk",
  "e170",
  "ins 170"
 ],
 "calcium caseinate": [
  "calcium caseinate",
  "casein",
  "caseinate",
  "milk protein",
  "sodium caseinate"
 ],
 "calcium propionate": [
  "calcium propionate",
  "e282",
  "ins 282"
 ],
 "cane jaggery": [
  "cane jaggery",
  "gud",
  "gur",
  "jaggery"
 ],
 "cane sugar": [
  "cane sugar",
  "chini",
  "refined sugar",
  "sucrose",
  "sugar",
  "white sugar"
 ],
 "canola oil": [
  "canola",
  "canola oil",
  "rapeseed oil"
 ],
 "canola": [
  "canola",
  "canola oil",
  "rapeseed oil"
 ],
 "caramel color": [
  "caramel color",
  "caramel colour",
  "e150",
  "ins 150a",
  "ins 150b",
  "ins 150c",
  "ins 150d"
 ],
 "caramel colour": [
  "caramel color",
  "caramel colour",
  "e150",
  "ins 150a",
  "ins 150b",
  "ins 150c",
  "ins 150d"
 ],
 "carboxymethyl cellulose": [
  "carboxymethyl cellulose",
  "cellulose gum",
  "cmc",
  "e466",
  "ins 466"
 ],
 "carmine": [
  "carmine",
  "carminic acid",
  "cochineal",
  "e120",
  "ins 120"
 ],
 "carminic acid": [
  "carmine",
  "carminic acid",
  "cochineal",
  "e120",
  "ins 120"
 ],
 "carmoisine": [
  "azorubine",
  "carmoisine",
  "e122",
  "ins 122"
 ],
 "carob gum": [
  "carob gum",
  "e410",
  "ins 410",
  "locust bean gum"
 ],
 "carotene": [
  "beta carotene",
  "beta-carotene",
  "carotene",
  "e160a",
  "ins 160a"
 ],
 "carrageenan": [
  "carrageenan",
  "e407",
  "ins 407"
 ],
 "carrot": [
  "carrot",
  "gajar"
 ],
 "casein": [
  "calcium caseinate",
  "casein",
  "caseinate",
  "milk protein",
  "sodium caseinate"
 ],
 "caseinate": [
  "calcium caseinate",
  "casein",
  "caseinate",
  "milk protein",
  "sodium caseinate"
 ],
 "cashew butter": [
  "akhrot",
  "almond",
  "almond butter",
  "almond milk",
  "badam",
  "brazil nut",
  "cashew",
  "cashew butter",
  "cashew nut",
  "chilgoza",
  "dry fruit",
  "dry fruits",
  "dryfruit",
  "dryfruits",
  "hazelnut",
  "kaju",
  "macadamia",
  "marzipan",
  "pecan",
  "pine nut",
  "pista",
  "pistachio",
  "tree nuts",
  "walnut"
 ],
 "cashew nut": [
  "akhrot",
  "almond",
  "almond butter",
  "almond milk",
  "badam",
  "brazil nut",
  "cashew",
  "cashew butter",
  "cashew nut",
  "chilgoza",
  "dry fruit",
  "dry fruits",
  "dryfruit",
  "dryfruits",
  "hazelnut",
  "kaju",
  "macadamia",
  "marzipan",
  "pecan",
  "pine nut",
  "pista",
  "pistachio",
  "tree nuts",
  "walnut"
 ],
 "cashew": [
  "akhrot",
  "almond",
  "almond butter",
  "almond milk",
  "badam",
  "brazil nut",
  "cashew",
  "cashew butter",
  "cashew nut",
  "chilgoza",
  "dry fruit",
  "dry fruits",
  "dryfruit",
  "dryfruits",
  "hazelnut",
  "kaju",
  "macadamia",
  "marzipan",
  "pecan",
  "pine nut",
  "pista",
  "pistachio",
  "tree nuts",
  "walnut"
 ],
 "cassava starch": [
  "cassava starch",
  "sabudana",
  "sago",
  "tapioca",
  "tapioca starch"
 ],
 "cayenne": [
  "cayenne",
  "chili",
  "chilli",
  "chilli flakes",
  "chilli powder",
  "green chilli",
  "kashmiri chilli",
  "lal mirch",
  "mirchi",
  "red chilli",
  "red chilli powder"
 ],
 "cellulose gum": [
  "carboxymethyl cellulose",
  "cellulose gum",
  "cmc",
  "e466",
  "ins 466"
 ],
 "cereals containing gluten": [
  "cereals containing gluten",
  "gluten",
  "malt",
  "malt extract",
  "malted",
  "malted barley",
  "rye",
  "triticale",
  "vital gluten",
  "wheat gluten"
 ],
 "chaas": [
  "butter",
  "buttermilk",
  "chaas",
  "cheese",
  "chhena",
  "cream",
  "curd",
  "dahi",
  "dairy",
  "khoya",
  "lactose",
  "makhan",
  "malai",
  "mawa",
  "milk",
  "milk fat",
  "milk powder",
  "milk solids",
  "milkfat",
  "paneer",
  "skimmed milk powder",
  "smp",
  "yoghurt",
  "yogurt"
 ],
 "chakki atta": [
  "aata",
  "aatta",
  "ata",
  "atta",
  "chakki atta",
  "gehun atta",
  "whole meal flour",
  "whole wheat flour",
  "wholewheat flour"
 ],
 "chalk": [
  "calcium carbonate",
  "chalk",
  "e170",
  "ins 170"
 ],
 "chana dal": [
  "besan",
  "chana",
  "chana dal",
  "chickpea",
  "gram flour",
  "kabuli chana"
 ],
 "chana": [
  "besan",
  "chana",
  "chana dal",
  "chickpea",
  "gram flour",
  "kabuli chana"
 ],
 "chaval": [
  "basmati rice",
  "chaval",
  "chawal",
  "polished rice",
  "white rice"
 ],
 "chawal atta": [
  "chawal atta",
  "rice flour"
 ],
 "chawal": [
  "basmati rice",
  "chaval",
  "chawal",
  "polished rice",
  "white rice"
 ],
 "cheese": [
  "butter",
  "buttermilk",
  "chaas",
  "cheese",
  "chhena",
  "cream",
  "curd",
  "dahi",
  "dairy",
  "khoya",
  "lactose",
  "makhan",
  "malai",
  "mawa",
  "milk",
  "milk fat",
  "milk powder",
  "milk solids",
  "milkfat",
  "paneer",
  "skimmed milk powder",
  "smp",
  "yoghurt",
  "yogurt"
 ],
 "chhena": [
  "butter",
  "buttermilk",
  "chaas",
  "cheese",
  "chhena",
  "cream",
  "curd",
  "dahi",
  "dairy",
  "khoya",
  "lactose",
  "makhan",
  "malai",
  "mawa",
  "milk",
  "milk fat",
  "milk powder",
  "milk solids",
  "milkfat",
  "paneer",
  "skimmed milk powder",
  "smp",
  "yoghurt",
  "yogurt"
 ],
 "chia seeds": [
  "chia",
  "chia seeds",
  "sabja substitute"
 ],
 "chia": [
  "chia",
  "chia seeds",
  "sabja substitute"
 ],
 "chickpea": [
  "besan",
  "chana",
  "chana dal",
  "chickpea",
  "gram flour",
  "kabuli chana"
 ],
 "chicory inulin": [
  "chicory inulin",
  "chicory root fibre",
  "fos",
  "fructooligosaccharide",
  "inulin"
 ],
 "chicory root fibre": [
  "chicory inulin",
  "chicory root fibre",
  "fos",
  "fructooligosaccharide",
  "inulin"
 ],
 "chilgoza": [
  "akhrot",
  "almond",
  "almond butter",
  "almond milk",
  "badam",
  "brazil nut",
  "cashew",
  "cashew butter",
  "cashew nut",
  "chilgoza",
  "dry fruit",
  "dry fruits",
  "dryfruit",
  "dryfruits",
  "hazelnut",
  "kaju",
  "macadamia",
  "marzipan",
  "pecan",
  "pine nut",
  "pista",
  "pistachio",
  "tree nuts",
  "walnut"
 ],
 "chili": [
  "cayenne",
  "chili",
  "chilli",
  "chilli flakes",
  "chilli powder",
  "green chilli",
  "kashmiri chilli",
  "lal mirch",
  "mirchi",
  "red chilli",
  "red chilli powder"
 ],
 "chilli flakes": [
  "cayenne",
  "chili",
  "chilli",
  "chilli flakes",
  "chilli powder",
  "green chilli",
  "kashmiri chilli",
  "lal mirch",
  "mirchi",
  "red chilli",
  "red chilli powder"
 ],
 "chilli powder": [
  "cayenne",
  "chili",
  "chilli",
  "chilli flakes",
  "chilli powder",
  "green chilli",
  "kashmiri chilli",
  "lal mirch",
  "mirchi",
  "red chilli",
  "red chilli powder"
 ],
 "chilli": [
  "cayenne",
  "chili",
  "chilli",
  "chilli flakes",
  "chilli powder",
  "green chilli",
  "kashmiri chilli",
  "lal mirch",
  "mirchi",
  "red chilli",
  "red chilli powder"
 ],
 "chini": [
  "cane sugar",
  "chini",
  "refined sugar",
  "sucrose",
  "sugar",
  "white sugar"
 ],
 "chukandar": [
  "beetroot",
  "chukandar"
 ],
 "citric acid": [
  "citric acid",
  "e330",
  "ins 330"
 ],
 "clarified butter": [
  "clarified butter",
  "desi ghee",
  "ghee"
 ],
 "cmc": [
  "carboxymethyl cellulose",
  "cellulose gum",
  "cmc",
  "e466",
  "ins 466"
 ],
 "cochineal red a": [
  "cochineal red a",
  "e124",
  "ins 124",
  "ponceau 4r"
 ],
 "cochineal": [
  "carmine",
  "carminic acid",
  "cochineal",
  "e120",
  "ins 120"
 ],
 "cocoa mass": [
  "cacao",
  "cocoa",
  "cocoa mass",
  "cocoa powder",
  "cocoa solids"
 ],
 "cocoa powder": [
  "cacao",
  "cocoa",
  "cocoa mass",
  "cocoa powder",
  "cocoa solids"
 ],
 "cocoa solids": [
  "cacao",
  "cocoa",
  "cocoa mass",
  "cocoa powder",
  "cocoa solids"
 ],
 "cocoa": [
  "cacao",
  "cocoa",
  "cocoa mass",
  "cocoa powder",
  "cocoa solids"
 ],
 "coconut cream": [
  "coconut cream",
  "coconut milk",
  "coconut milk powder",
  "coconut milk solids"
 ],
 "coconut milk powder": [
  "coconut cream",
  "coconut milk",
  "coconut milk powder",
  "coconut milk solids"
 ],
 "coconut milk solids": [
  "coconut cream",
  "coconut milk",
  "coconut milk powder",
  "coconut milk solids"
 ],
 "coconut milk": [
  "coconut cream",
  "coconut milk",
  "coconut milk powder",
  "coconut milk solids"
 ],
 "coconut oil": [
  "coconut oil",
  "nariyal tel",
  "virgin coconut oil"
 ],
 "coffee extract": [
  "coffee",
  "coffee extract",
  "coffee powder",
  "espresso",
  "instant coffee"
 ],
 "coffee powder": [
  "coffee",
  "coffee extract",
  "coffee powder",
  "espresso",
  "instant coffee"
 ],
 "coffee": [
  "coffee",
  "coffee extract",
  "coffee powder",
  "espresso",
  "instant coffee"
 ],
 "colocasia": [
  "arbi",
  "colocasia",
  "taro"
 ],
 "common salt": [
  "common salt",
  "iodised salt",
  "iodized salt",
  "namak",
  "salt",
  "table salt"
 ],
 "confectioners glaze": [
  "confectioners glaze",
  "e904",
  "ins 904",
  "shellac"
 ],
 "corn flour": [
  "corn flour",
  "corn starch",
  "cornflour",
  "maize starch",
  "makai starch"
 ],
 "corn starch": [
  "corn flour",
  "corn starch",
  "cornflour",
  "maize starch",
  "makai starch"
 ],
 "corn syrup": [
  "corn syrup",
  "fructose syrup",
  "glucose fructose syrup",
  "hfcs",
  "high fructose corn syrup"
 ],
 "cornflour": [
  "corn flour",
  "corn starch",
  "cornflour",
  "maize starch",
  "makai starch"
 ],
 "cottonseed oil": [
  "binola oil",
  "cottonseed oil"
 ],
 "couscous": [
  "bread",
  "bread crumbs",
  "breadcrumbs",
  "couscous",
  "durum",
  "pasta",
  "rava",
  "semolina",
  "suji",
  "wheat",
  "wheat flour",
  "whole wheat",
  "wholewheat"
 ],
 "crab": [
  "crab",
  "crustacean",
  "crustacean shellfish",
  "jhinga",
  "krill",
  "lobster",
  "prawn",
  "shellfish",
  "shrimp"
 ],
 "cream": [
  "butter",
  "buttermilk",
  "chaas",
  "cheese",
  "chhena",
  "cream",
  "curd",
  "dahi",
  "dairy",
  "khoya",
  "lactose",
  "makhan",
  "malai",
  "mawa",
  "milk",
  "milk fat",
  "milk powder",
  "milk solids",
  "milkfat",
  "paneer",
  "skimmed milk powder",
  "smp",
  "yoghurt",
  "yogurt"
 ],
 "crustacean shellfish": [
  "crab",
  "crustacean",
  "crustacean shellfish",
  "jhinga",
  "krill",
  "lobster",
  "prawn",
  "shellfish",
  "shrimp"
 ],
 "crustacean": [
  "crab",
  "crustacean",
  "crustacean shellfish",
  "jhinga",
  "krill",
  "lobster",
  "prawn",
  "shellfish",
  "shrimp"
 ],
 "curcuma": [
  "curcuma",
  "haldi",
  "turmeric"
 ],
 "curcumin": [
  "curcumin",
  "e100",
  "ins 100",
  "turmeric colour"
 ],
 "curd": [
  "butter",
  "buttermilk",
  "chaas",
  "cheese",
  "chhena",
  "cream",
  "curd",
  "dahi",
  "dairy",
  "khoya",
  "lactose",
  "makhan",
  "malai",
  "mawa",
  "milk",
  "milk fat",
  "milk powder",
  "milk solids",
  "milkfat",
  "paneer",
  "skimmed milk powder",
  "smp",
  "yoghurt",
  "yogurt"
 ],
 "daal": [
  "arhar",
  "daal",
  "dal",
  "dhal",
  "lentil",
  "lentils",
  "masoor",
  "moong",
  "pulse",
  "toor",
  "urad"
 ],
 "dahi culture": [
  "bifidobacterium",
  "dahi culture",
  "lactobacillus",
  "live cultures",
  "probiotic cultures",
  "yoghurt culture",
  "yoghurt cultures"
 ],
 "dahi": [
  "butter",
  "buttermilk",
  "chaas",
  "cheese",
  "chhena",
  "cream",
  "curd",
  "dahi",
  "dairy",
  "khoya",
  "lactose",
  "makhan",
  "malai",
  "mawa",
  "milk",
  "milk fat",
  "milk powder",
  "milk solids",
  "milkfat",
  "paneer",
  "skimmed milk powder",
  "smp",
  "yoghurt",
  "yogurt"
 ],
 "dairy": [
  "butter",
  "buttermilk",
  "chaas",
  "cheese",
  "chhena",
  "cream",
  "curd",
  "dahi",
  "dairy",
  "khoya",
  "lactose",
  "makhan",
  "malai",
  "mawa",
  "milk",
  "milk fat",
  "milk powder",
  "milk solids",
  "milkfat",
  "paneer",
  "skimmed milk powder",
  "smp",
  "yoghurt",
  "yogurt"
 ],
 "dal": [
  "arhar",
  "daal",
  "dal",
  "dhal",
  "lentil",
  "lentils",
  "masoor",
  "moong",
  "pulse",
  "toor",
  "urad"
 ],
 "dalda": [
  "dalda",
  "hydrogenated vegetable oil",
  "vanaspati",
  "vanaspati ghee",
  "vegetable ghee"
 ],
 "date paste": [
  "date paste",
  "date syrup",
  "khajur syrup"
 ],
 "date syrup": [
  "date paste",
  "date syrup",
  "khajur syrup"
 ],
 "dates": [
  "dates",
  "khajur",
  "medjool"
 ],
 "dehydrated onion": [
  "dehydrated onion",
  "kanda",
  "onion",
  "onion powder",
  "pyaaz",
  "pyaz"
 ],
 "dehydrated potato": [
  "aloo",
  "dehydrated potato",
  "potato",
  "potato flakes",
  "potato powder"
 ],
 "desi ghee": [
  "clarified butter",
  "desi ghee",
  "ghee"
 ],
 "dextrose monohydrate": [
  "dextrose",
  "dextrose monohydrate",
  "glucose",
  "glucose syrup",
  "liquid glucose"
 ],
 "dextrose": [
  "dextrose",
  "dextrose monohydrate",
  "glucose",
  "glucose syrup",
  "liquid glucose"
 ],
 "dhal": [
  "arhar",
  "daal",
  "dal",
  "dhal",
  "lentil",
  "lentils",
  "masoor",
  "moong",
  "pulse",
  "toor",
  "urad"
 ],
 "diglycerides": [
  "diglycerides",
  "e471",
  "ins 471",
  "mono and diglycerides",
  "mono- and diglycerides",
  "monoglycerides"
 ],
 "diphosphate": [
  "diphosphate",
  "diphosphates",
  "e450",
  "ins 450",
  "sapp",
  "sodium acid pyrophosphate"
 ],
 "diphosphates": [
  "diphosphate",
  "diphosphates",
  "e450",
  "ins 450",
  "sapp",
  "sodium acid pyrophosphate"
 ],
 "disodium guanylate": [
  "disodium guanylate",
  "e627",
  "ins 627"
 ],
 "disodium inosinate": [
  "disodium inosinate",
  "e631",
  "ins 631"
 ],
 "disodium ribonucleotides": [
  "disodium ribonucleotides",
  "e635",
  "ins 635"
 ],
 "drumstick leaf": [
  "drumstick leaf",
  "moringa",
  "moringa oleifera",
  "sahjan"
 ],
 "dry fruit": [
  "akhrot",
  "almond",
  "almond butter",
  "almond milk",
  "badam",
  "brazil nut",
  "cashew",
  "cashew butter",
  "cashew nut",
  "chilgoza",
  "dry fruit",
  "dry fruits",
  "dryfruit",
  "dryfruits",
  "hazelnut",
  "kaju",
  "macadamia",
  "marzipan",
  "pecan",
  "pine nut",
  "pista",
  "pistachio",
  "tree nuts",
  "walnut"
 ],
 "dry fruits": [
  "akhrot",
  "almond",
  "almond butter",
  "almond milk",
  "badam",
  "brazil nut",
  "cashew",
  "cashew butter",
  "cashew nut",
  "chilgoza",
  "dry fruit",
  "dry fruits",
  "dryfruit",
  "dryfruits",
  "hazelnut",
  "kaju",
  "macadamia",
  "marzipan",
  "pecan",
  "pine nut",
  "pista",
  "pistachio",
  "tree nuts",
  "walnut"
 ],
 "dry ginger": [
  "adrak",
  "dry ginger",
  "ginger",
  "ginger powder",
  "sonth"
 ],
 "dryfruit": [
  "akhrot",
  "almond",
  "almond butter",
  "almond milk",
  "badam",
  "brazil nut",
  "cashew",
  "cashew butter",
  "cashew nut",
  "chilgoza",
  "dry fruit",
  "dry fruits",
  "dryfruit",
  "dryfruits",
  "hazelnut",
  "kaju",
  "macadamia",
  "marzipan",
  "pecan",
  "pine nut",
  "pista",
  "pistachio",
  "tree nuts",
  "walnut"
 ],
 "dryfruits": [
  "akhrot",
  "almond",
  "almond butter",
  "almond milk",
  "badam",
  "brazil nut",
  "cashew",
  "cashew butter",
  "cashew nut",
  "chilgoza",
  "dry fruit",
  "dry fruits",
  "dryfruit",
  "dryfruits",
  "hazelnut",
  "kaju",
  "macadamia",
  "marzipan",
  "pecan",
  "pine nut",
  "pista",
  "pistachio",
  "tree nuts",
  "walnut"
 ],
 "durum": [
  "bread",
  "bread crumbs",
  "breadcrumbs",
  "couscous",
  "durum",
  "pasta",
  "rava",
  "semolina",
  "suji",
  "wheat",
  "wheat flour",
  "whole wheat",
  "wholewheat"
 ],
 "e100": [
  "curcumin",
  "e100",
  "ins 100",
  "turmeric colour"
 ],
 "e102": [
  "e102",
  "fd c yellow 5",
  "ins 102",
  "tartrazine",
  "yellow 5"
 ],
 "e104": [
  "e104",
  "ins 104",
  "quinoline yellow"
 ],
 "e110": [
  "e110",
  "fd c yellow 6",
  "ins 110",
  "sunset yellow",
  "sunset yellow fcf",
  "yellow 6"
 ],
 "e1105": [
  "e1105",
  "ins 1105",
  "lysozyme"
 ],
 "e120": [
  "carmine",
  "carminic acid",
  "cochineal",
  "e120",
  "ins 120"
 ],
 "e122": [
  "azorubine",
  "carmoisine",
  "e122",
  "ins 122"
 ],
 "e124": [
  "cochineal red a",
  "e124",
  "ins 124",
  "ponceau 4r"
 ],
 "e127": [
  "e127",
  "erythrosine",
  "fd c red 3",
  "ins 127",
  "red 3"
 ],
 "e129": [
  "allura red",
  "allura red ac",
  "e129",
  "fd c red 40",
  "ins 129",
  "red 40"
 ],
 "e132": [
  "e132",
  "indigo carmine",
  "indigotine",
  "ins 132"
 ],
 "e133": [
  "brilliant blue",
  "brilliant blue fcf",
  "e133",
  "fd c blue 1",
  "ins 133"
 ],
 "e1422": [
  "acetylated distarch adipate",
  "e1422",
  "ins 1422",
  "modified corn starch",
  "modified starch"
 ],
 "e143": [
  "e143",
  "fast green",
  "fast green fcf",
  "fd c green 3",
  "ins 143"
 ],
 "e150": [
  "caramel color",
  "caramel colour",
  "e150",
  "ins 150a",
  "ins 150b",
  "ins 150c",
  "ins 150d"
 ],
 "e160a": [
  "beta carotene",
  "beta-carotene",
  "carotene",
  "e160a",
  "ins 160a"
 ],
 "e160b": [
  "annatto",
  "bixin",
  "e160b",
  "ins 160b",
  "norbixin"
 ],
 "e160c": [
  "e160c",
  "ins 160c",
  "paprika extract",
  "paprika oleoresin"
 ],
 "e162": [
  "beetroot red",
  "betanin",
  "e162",
  "ins 162"
 ],
 "e163": [
  "anthocyanin",
  "anthocyanins",
  "e163",
  "grape skin extract",
  "ins 163"
 ],
 "e170": [
  "calcium carbonate",
  "chalk",
  "e170",
  "ins 170"
 ],
 "e171": [
  "e171",
  "ins 171",
  "titanium dioxide"
 ],
 "e200": [
  "e200",
  "ins 200",
  "sorbic acid"
 ],
 "e202": [
  "e202",
  "ins 202",
  "potassium sorbate"
 ],
 "e210": [
  "benzoic acid",
  "e210",
  "ins 210"
 ],
 "e211": [
  "benzoate",
  "e211",
  "ins 211",
  "sodium benzoate"
 ],
 "e220": [
  "e220",
  "ins 220",
  "sulfur dioxide",
  "sulphur dioxide"
 ],
 "e223": [
  "e223",
  "ins 223",
  "metabisulphite",
  "sodium metabisulfite",
  "sodium metabisulphite"
 ],
 "e224": [
  "e224",
  "ins 224",
  "potassium metabisulphite"
 ],
 "e234": [
  "e234",
  "ins 234",
  "nisin"
 ],
 "e235": [
  "e235",
  "ins 235",
  "natamycin",
  "pimaricin"
 ],
 "e250": [
  "e250",
  "ins 250",
  "nitrite",
  "sodium nitrite"
 ],
 "e251": [
  "e251",
  "ins 251",
  "nitrate",
  "sodium nitrate"
 ],
 "e260": [
  "acetic acid",
  "e260",
  "ins 260",
  "vinegar"
 ],
 "e270": [
  "e270",
  "ins 270",
  "lactic acid"
 ],
 "e282": [
  "calcium propionate",
  "e282",
  "ins 282"
 ],
 "e296": [
  "e296",
  "ins 296",
  "malic acid"
 ],
 "e300": [
  "ascorbic acid",
  "e300",
  "ins 300",
  "vitamin c"
 ],
 "e306": [
  "e306",
  "e307",
  "ins 306",
  "ins 307",
  "mixed tocopherols",
  "tocopherol",
  "tocopherols",
  "vitamin e"
 ],
 "e307": [
  "e306",
  "e307",
  "ins 306",
  "ins 307",
  "mixed tocopherols",
  "tocopherol",
  "tocopherols",
  "vitamin e"
 ],
 "e319": [
  "e319",
  "ins 319",
  "tbhq",
  "tertiary butylhydroquinone"
 ],
 "e320": [
  "bha",
  "butylated hydroxyanisole",
  "e320",
  "ins 320"
 ],
 "e321": [
  "bht",
  "butylated hydroxytoluene",
  "e321",
  "ins 321"
 ],
 "e322": [
  "e322",
  "ins 322",
  "lecithin",
  "soy lecithin",
  "soya lecithin"
 ],
 "e330": [
  "citric acid",
  "e330",
  "ins 330"
 ],
 "e331": [
  "e331",
  "ins 331",
  "sodium citrate",
  "trisodium citrate"
 ],
 "e338": [
  "e338",
  "ins 338",
  "phosphoric acid"
 ],
 "e407": [
  "carrageenan",
  "e407",
  "ins 407"
 ],
 "e410": [
  "carob gum",
  "e410",
  "ins 410",
  "locust bean gum"
 ],
 "e412": [
  "e412",
  "guar gum",
  "ins 412"
 ],
 "e414": [
  "acacia gum",
  "e414",
  "gum arabic",
  "ins 414"
 ],
 "e415": [
  "e415",
  "ins 415",
  "xanthan gum"
 ],
 "e420": [
  "e420",
  "ins 420",
  "sorbitol"
 ],
 "e422": [
  "e422",
  "glycerin",
  "glycerine",
  "glycerol",
  "ins 422"
 ],
 "e433": [
  "e433",
  "ins 433",
  "polysorbate 80",
  "tween 80"
 ],
 "e440": [
  "e440",
  "ins 440",
  "pectin"
 ],
 "e450": [
  "diphosphate",
  "diphosphates",
  "e450",
  "ins 450",
  "sapp",
  "sodium acid pyrophosphate"
 ],
 "e452": [
  "e452",
  "ins 452",
  "polyphosphate",
  "polyphosphates",
  "sodium polyphosphate"
 ],
 "e466": [
  "carboxymethyl cellulose",
  "cellulose gum",
  "cmc",
  "e466",
  "ins 466"
 ],
 "e471": [
  "diglycerides",
  "e471",
  "ins 471",
  "mono and diglycerides",
  "mono- and diglycerides",
  "monoglycerides"
 ],
 "e500": [
  "baking soda",
  "e500",
  "ins 500",
  "sodium bicarbonate"
 ],
 "e508": [
  "e508",
  "ins 508",
  "low sodium salt",
  "potassium chloride"
 ],
 "e541": [
  "e541",
  "ins 541",
  "sodium aluminium phosphate"
 ],
 "e551": [
  "e551",
  "ins 551",
  "silica",
  "silicon dioxide"
 ],
 "e554": [
  "e554",
  "ins 554",
  "sodium aluminosilicate"
 ],
 "e621": [
  "ajinomoto",
  "e621",
  "flavour enhancer 621",
  "ins 621",
  "monosodium glutamate",
  "msg",
  "taste maker"
 ],
 "e627": [
  "disodium guanylate",
  "e627",
  "ins 627"
 ],
 "e631": [
  "disodium inosinate",
  "e631",
  "ins 631"
 ],
 "e635": [
  "disodium ribonucleotides",
  "e635",
  "ins 635"
 ],
 "e904": [
  "confectioners glaze",
  "e904",
  "ins 904",
  "shellac"
 ],
 "e924": [
  "bromate",
  "e924",
  "ins 924",
  "potassium bromate"
 ],
 "e950": [
  "ace k",
  "acesulfame k",
  "acesulfame potassium",
  "e950",
  "ins 950"
 ],
 "e951": [
  "aspartame",
  "e951",
  "ins 951"
 ],
 "e954": [
  "e954",
  "ins 954",
  "saccharin"
 ],
 "e955": [
  "e955",
  "ins 955",
  "sucralose"
 ],
 "e960": [
  "e960",
  "ins 960",
  "stevia",
  "steviol glycosides"
 ],
 "e961": [
  "e961",
  "ins 961",
  "neotame"
 ],
 "e965": [
  "e965",
  "ins 965",
  "maltitol"
 ],
 "e967": [
  "e967",
  "ins 967",
  "xylitol"
 ],
 "e968": [
  "e968",
  "erythritol",
  "ins 968"
 ],
 "egg powder": [
  "albumen",
  "albumin",
  "anda",
  "egg",
  "egg powder",
  "egg white",
  "egg yolk",
  "liquid egg"
 ],
 "egg white": [
  "albumen",
  "albumin",
  "anda",
  "egg",
  "egg powder",
  "egg white",
  "egg yolk",
  "liquid egg"
 ],
 "egg yolk": [
  "albumen",
  "albumin",
  "anda",
  "egg",
  "egg powder",
  "egg white",
  "egg yolk",
  "liquid egg"
 ],
 "egg": [
  "albumen",
  "albumin",
  "anda",
  "egg",
  "egg powder",
  "egg white",
  "egg yolk",
  "liquid egg"
 ],
 "erythritol": [
  "e968",
  "erythritol",
  "ins 968"
 ],
 "erythrosine": [
  "e127",
  "erythrosine",
  "fd c red 3",
  "ins 127",
  "red 3"
 ],
 "espresso": [
  "coffee",
  "coffee extract",
  "coffee powder",
  "espresso",
  "instant coffee"
 ],
 "evoo": [
  "evoo",
  "extra virgin olive oil",
  "olive oil"
 ],
 "extra virgin olive oil": [
  "evoo",
  "extra virgin olive oil",
  "olive oil"
 ],
 "fast green fcf": [
  "e143",
  "fast green",
  "fast green fcf",
  "fd c green 3",
  "ins 143"
 ],
 "fast green": [
  "e143",
  "fast green",
  "fast green fcf",
  "fd c green 3",
  "ins 143"
 ],
 "fd c blue 1": [
  "brilliant blue",
  "brilliant blue fcf",
  "e133",
  "fd c blue 1",
  "ins 133"
 ],
 "fd c green 3": [
  "e143",
  "fast green",
  "fast green fcf",
  "fd c green 3",
  "ins 143"
 ],
 "fd c red 3": [
  "e127",
  "erythrosine",
  "fd c red 3",
  "ins 127",
  "red 3"
 ],
 "fd c red 40": [
  "allura red",
  "allura red ac",
  "e129",
  "fd c red 40",
  "ins 129",
  "red 40"
 ],
 "fd c yellow 5": [
  "e102",
  "fd c yellow 5",
  "ins 102",
  "tartrazine",
  "yellow 5"
 ],
 "fd c yellow 6": [
  "e110",
  "fd c yellow 6",
  "ins 110",
  "sunset yellow",
  "sunset yellow fcf",
  "yellow 6"
 ],
 "finger millet": [
  "finger millet",
  "nachni",
  "ragi",
  "ragi flour"
 ],
 "fish oil": [
  "anchovy",
  "fish",
  "fish oil",
  "fish sauce",
  "machhli",
  "machli",
  "salmon",
  "sardine",
  "tuna"
 ],
 "fish sauce": [
  "anchovy",
  "fish",
  "fish oil",
  "fish sauce",
  "machhli",
  "machli",
  "salmon",
  "sardine",
  "tuna"
 ],
 "fish": [
  "anchovy",
  "fish",
  "fish oil",
  "fish sauce",
  "machhli",
  "machli",
  "salmon",
  "sardine",
  "tuna"
 ],
 "flavour enhancer 621": [
  "ajinomoto",
  "e621",
  "flavour enhancer 621",
  "ins 621",
  "monosodium glutamate",
  "msg",
  "taste maker"
 ],
 "flax seeds": [
  "alsi",
  "flax seeds",
  "flaxseed",
  "linseed"
 ],
 "flaxseed": [
  "alsi",
  "flax seeds",
  "flaxseed",
  "linseed"
 ],
 "fos": [
  "chicory inulin",
  "chicory root fibre",
  "fos",
  "fructooligosaccharide",
  "inulin"
 ],
 "fox nut": [
  "fox nut",
  "lotus seed",
  "makhana",
  "phool makhana"
 ],
 "foxtail millet": [
  "foxtail millet",
  "kangni",
  "navane"
 ],
 "fructooligosaccharide": [
  "chicory inulin",
  "chicory root fibre",
  "fos",
  "fructooligosaccharide",
  "inulin"
 ],
 "fructose syrup": [
  "corn syrup",
  "fructose syrup",
  "glucose fructose syrup",
  "hfcs",
  "high fructose corn syrup"
 ],
 "gajar": [
  "carrot",
  "gajar"
 ],
 "garlic powder": [
  "garlic",
  "garlic powder",
  "lahsun",
  "lehsun"
 ],
 "garlic": [
  "garlic",
  "garlic powder",
  "lahsun",
  "lehsun"
 ],
 "gehun atta": [
  "aata",
  "aatta",
  "ata",
  "atta",
  "chakki atta",
  "gehun atta",
  "whole meal flour",
  "whole wheat flour",
  "wholewheat flour"
 ],
 "gelatin": [
  "gelatin",
  "gelatine"
 ],
 "gelatine": [
  "gelatin",
  "gelatine"
 ],
 "ghee": [
  "clarified butter",
  "desi ghee",
  "ghee"
 ],
 "gingelly oil": [
  "gingelly oil",
  "sesame oil",
  "til oil"
 ],
 "gingelly": [
  "gingelly",
  "sesame",
  "sesame seeds",
  "tahini",
  "til"
 ],
 "ginger powder": [
  "adrak",
  "dry ginger",
  "ginger",
  "ginger powder",
  "sonth"
 ],
 "ginger": [
  "adrak",
  "dry ginger",
  "ginger",
  "ginger powder",
  "sonth"
 ],
 "glucose fructose syrup": [
  "corn syrup",
  "fructose syrup",
  "glucose fructose syrup",
  "hfcs",
  "high fructose corn syrup"
 ],
 "glucose syrup": [
  "dextrose",
  "dextrose monohydrate",
  "glucose",
  "glucose syrup",
  "liquid glucose"
 ],
 "glucose": [
  "dextrose",
  "dextrose monohydrate",
  "glucose",
  "glucose syrup",
  "liquid glucose"
 ],
 "gluten": [
  "cereals containing gluten",
  "gluten",
  "malt",
  "malt extract",
  "malted",
  "malted barley",
  "rye",
  "triticale",
  "vital gluten",
  "wheat gluten"
 ],
 "glycerin": [
  "e422",
  "glycerin",
  "glycerine",
  "glycerol",
  "ins 422"
 ],
 "glycerine": [
  "e422",
  "glycerin",
  "glycerine",
  "glycerol",
  "ins 422"
 ],
 "glycerol": [
  "e422",
  "glycerin",
  "glycerine",
  "glycerol",
  "ins 422"
 ],
 "goat meat": [
  "goat meat",
  "mutton"
 ],
 "gram flour": [
  "besan",
  "chana",
  "chana dal",
  "chickpea",
  "gram flour",
  "kabuli chana"
 ],
 "grape skin extract": [
  "anthocyanin",
  "anthocyanins",
  "e163",
  "grape skin extract",
  "ins 163"
 ],
 "green chilli": [
  "cayenne",
  "chili",
  "chilli",
  "chilli flakes",
  "chilli powder",
  "green chilli",
  "kashmiri chilli",
  "lal mirch",
  "mirchi",
  "red chilli",
  "red chilli powder"
 ],
 "green tea extract": [
  "black tea",
  "green tea",
  "green tea extract",
  "tea",
  "tea extract",
  "tea leaves",
  "tea powder"
 ],
 "green tea": [
  "black tea",
  "green tea",
  "green tea extract",
  "tea",
  "tea extract",
  "tea leaves",
  "tea powder"
 ],
 "groundnut oil": [
  "arachis oil",
  "groundnut oil",
  "peanut oil"
 ],
 "groundnut": [
  "groundnut",
  "moongfali",
  "moongphali",
  "mungfali",
  "peanut",
  "peanut butter",
  "peanuts",
  "shengdana",
  "singdana"
 ],
 "guar gum": [
  "e412",
  "guar gum",
  "ins 412"
 ],
 "gud": [
  "cane jaggery",
  "gud",
  "gur",
  "jaggery"
 ],
 "gum arabic": [
  "acacia gum",
  "e414",
  "gum arabic",
  "ins 414"
 ],
 "gur": [
  "cane jaggery",
  "gud",
  "gur",
  "jaggery"
 ],
 "haldi": [
  "curcuma",
  "haldi",
  "turmeric"
 ],
 "ham": [
  "bacon",
  "ham",
  "pork"
 ],
 "hazelnut": [
  "akhrot",
  "almond",
  "almond butter",
  "almond milk",
  "badam",
  "brazil nut",
  "cashew",
  "cashew butter",
  "cashew nut",
  "chilgoza",
  "dry fruit",
  "dry fruits",
  "dryfruit",
  "dryfruits",
  "hazelnut",
  "kaju",
  "macadamia",
  "marzipan",
  "pecan",
  "pine nut",
  "pista",
  "pistachio",
  "tree nuts",
  "walnut"
 ],
 "hfcs": [
  "corn syrup",
  "fructose syrup",
  "glucose fructose syrup",
  "hfcs",
  "high fructose corn syrup"
 ],
 "high fructose corn syrup": [
  "corn syrup",
  "fructose syrup",
  "glucose fructose syrup",
  "hfcs",
  "high fructose corn syrup"
 ],
 "himalayan salt": [
  "himalayan salt",
  "pink salt",
  "rock salt",
  "sendha namak"
 ],
 "honey": [
  "honey",
  "madhu",
  "shahad"
 ],
 "hvp": [
  "autolysed yeast",
  "hvp",
  "hydrolysed vegetable protein",
  "yeast extract"
 ],
 "hydrogenated vegetable fat": [
  "hydrogenated vegetable fat",
  "partially hydrogenated oil",
  "partially hydrogenated vegetable oil",
  "phvo"
 ],
 "hydrogenated vegetable oil": [
  "dalda",
  "hydrogenated vegetable oil",
  "vanaspati",
  "vanaspati ghee",
  "vegetable ghee"
 ],
 "hydrolysed vegetable protein": [
  "autolysed yeast",
  "hvp",
  "hydrolysed vegetable protein",
  "yeast extract"
 ],
 "indigo carmine": [
  "e132",
  "indigo carmine",
  "indigotine",
  "ins 132"
 ],
 "indigotine": [
  "e132",
  "indigo carmine",
  "indigotine",
  "ins 132"
 ],
 "industrial trans fat": [
  "industrial trans fat",
  "trans fat",
  "trans fatty acids"
 ],
 "ins 100": [
  "curcumin",
  "e100",
  "ins 100",
  "turmeric colour"
 ],
 "ins 102": [
  "e102",
  "fd c yellow 5",
  "ins 102",
  "tartrazine",
  "yellow 5"
 ],
 "ins 104": [
  "e104",
  "ins 104",
  "quinoline yellow"
 ],
 "ins 110": [
  "e110",
  "fd c yellow 6",
  "ins 110",
  "sunset yellow",
  "sunset yellow fcf",
  "yellow 6"
 ],
 "ins 1105": [
  "e1105",
  "ins 1105",
  "lysozyme"
 ],
 "ins 120": [
  "carmine",
  "carminic acid",
  "cochineal",
  "e120",
  "ins 120"
 ],
 "ins 122": [
  "azorubine",
  "carmoisine",
  "e122",
  "ins 122"
 ],
 "ins 124": [
  "cochineal red a",
  "e124",
  "ins 124",
  "ponceau 4r"
 ],
 "ins 127": [
  "e127",
  "erythrosine",
  "fd c red 3",
  "ins 127",
  "red 3"
 ],
 "ins 129": [
  "allura red",
  "allura red ac",
  "e129",
  "fd c red 40",
  "ins 129",
  "red 40"
 ],
 "ins 132": [
  "e132",
  "indigo carmine",
  "indigotine",
  "ins 132"
 ],
 "ins 133": [
  "brilliant blue",
  "brilliant blue fcf",
  "e133",
  "fd c blue 1",
  "ins 133"
 ],
 "ins 1422": [
  "acetylated distarch adipate",
  "e1422",
  "ins 1422",
  "modified corn starch",
  "modified starch"
 ],
 "ins 143": [
  "e143",
  "fast green",
  "fast green fcf",
  "fd c green 3",
  "ins 143"
 ],
 "ins 150a": [
  "caramel color",
  "caramel colour",
  "e150",
  "ins 150a",
  "ins 150b",
  "ins 150c",
  "ins 150d"
 ],
 "ins 150b": [
  "caramel color",
  "caramel colour",
  "e150",
  "ins 150a",
  "ins 150b",
  "ins 150c",
  "ins 150d"
 ],
 "ins 150c": [
  "caramel color",
  "caramel colour",
  "e150",
  "ins 150a",
  "ins 150b",
  "ins 150c",
  "ins 150d"
 ],
 "ins 150d": [
  "caramel color",
  "caramel colour",
  "e150",
  "ins 150a",
  "ins 150b",
  "ins 150c",
  "ins 150d"
 ],
 "ins 160a": [
  "beta carotene",
  "beta-carotene",
  "carotene",
  "e160a",
  "ins 160a"
 ],
 "ins 160b": [
  "annatto",
  "bixin",
  "e160b",
  "ins 160b",
  "norbixin"
 ],
 "ins 160c": [
  "e160c",
  "ins 160c",
  "paprika extract",
  "paprika oleoresin"
 ],
 "ins 162": [
  "beetroot red",
  "betanin",
  "e162",
  "ins 162"
 ],
 "ins 163": [
  "anthocyanin",
  "anthocyanins",
  "e163",
  "grape skin extract",
  "ins 163"
 ],
 "ins 170": [
  "calcium carbonate",
  "chalk",
  "e170",
  "ins 170"
 ],
 "ins 171": [
  "e171",
  "ins 171",
  "titanium dioxide"
 ],
 "ins 200": [
  "e200",
  "ins 200",
  "sorbic acid"
 ],
 "ins 202": [
  "e202",
  "ins 202",
  "potassium sorbate"
 ],
 "ins 210": [
  "benzoic acid",
  "e210",
  "ins 210"
 ],
 "ins 211": [
  "benzoate",
  "e211",
  "ins 211",
  "sodium benzoate"
 ],
 "ins 220": [
  "e220",
  "ins 220",
  "sulfur dioxide",
  "sulphur dioxide"
 ],
 "ins 223": [
  "e223",
  "ins 223",
  "metabisulphite",
  "sodium metabisulfite",
  "sodium metabisulphite"
 ],
 "ins 224": [
  "e224",
  "ins 224",
  "potassium metabisulphite"
 ],
 "ins 234": [
  "e234",
  "ins 234",
  "nisin"
 ],
 "ins 235": [
  "e235",
  "ins 235",
  "natamycin",
  "pimaricin"
 ],
 "ins 250": [
  "e250",
  "ins 250",
  "nitrite",
  "sodium nitrite"
 ],
 "ins 251": [
  "e251",
  "ins 251",
  "nitrate",
  "sodium nitrate"
 ],
 "ins 260": [
  "acetic acid",
  "e260",
  "ins 260",
  "vinegar"
 ],
 "ins 270": [
  "e270",
  "ins 270",
  "lactic acid"
 ],
 "ins 282": [
  "calcium propionate",
  "e282",
  "ins 282"
 ],
 "ins 296": [
  "e296",
  "ins 296",
  "malic acid"
 ],
 "ins 300": [
  "ascorbic acid",
  "e300",
  "ins 300",
  "vitamin c"
 ],
 "ins 306": [
  "e306",
  "e307",
  "ins 306",
  "ins 307",
  "mixed tocopherols",
  "tocopherol",
  "tocopherols",
  "vitamin e"
 ],
 "ins 307": [
  "e306",
  "e307",
  "ins 306",
  "ins 307",
  "mixed tocopherols",
  "tocopherol",
  "tocopherols",
  "vitamin e"
 ],
 "ins 319": [
  "e319",
  "ins 319",
  "tbhq",
  "tertiary butylhydroquinone"
 ],
 "ins 320": [
  "bha",
  "butylated hydroxyanisole",
  "e320",
  "ins 320"
 ],
 "ins 321": [
  "bht",
  "butylated hydroxytoluene",
  "e321",
  "ins 321"
 ],
 "ins 322": [
  "e322",
  "ins 322",
  "lecithin",
  "soy lecithin",
  "soya lecithin"
 ],
 "ins 330": [
  "citric acid",
  "e330",
  "ins 330"
 ],
 "ins 331": [
  "e331",
  "ins 331",
  "sodium citrate",
  "trisodium citrate"
 ],
 "ins 338": [
  "e338",
  "ins 338",
  "phosphoric acid"
 ],
 "ins 407": [
  "carrageenan",
  "e407",
  "ins 407"
 ],
 "ins 410": [
  "carob gum",
  "e410",
  "ins 410",
  "locust bean gum"
 ],
 "ins 412": [
  "e412",
  "guar gum",
  "ins 412"
 ],
 "ins 414": [
  "acacia gum",
  "e414",
  "gum arabic",
  "ins 414"
 ],
 "ins 415": [
  "e415",
  "ins 415",
  "xanthan gum"
 ],
 "ins 420": [
  "e420",
  "ins 420",
  "sorbitol"
 ],
 "ins 422": [
  "e422",
  "glycerin",
  "glycerine",
  "glycerol",
  "ins 422"
 ],
 "ins 433": [
  "e433",
  "ins 433",
  "polysorbate 80",
  "tween 80"
 ],
 "ins 440": [
  "e440",
  "ins 440",
  "pectin"
 ],
 "ins 450": [
  "diphosphate",
  "diphosphates",
  "e450",
  "ins 450",
  "sapp",
  "sodium acid pyrophosphate"
 ],
 "ins 452": [
  "e452",
  "ins 452",
  "polyphosphate",
  "polyphosphates",
  "sodium polyphosphate"
 ],
 "ins 466": [
  "carboxymethyl cellulose",
  "cellulose gum",
  "cmc",
  "e466",
  "ins 466"
 ],
 "ins 471": [
  "diglycerides",
  "e471",
  "ins 471",
  "mono and diglycerides",
  "mono- and diglycerides",
  "monoglycerides"
 ],
 "ins 500": [
  "baking soda",
  "e500",
  "ins 500",
  "sodium bicarbonate"
 ],
 "ins 508": [
  "e508",
  "ins 508",
  "low sodium salt",
  "potassium chloride"
 ],
 "ins 541": [
  "e541",
  "ins 541",
  "sodium aluminium phosphate"
 ],
 "ins 551": [
  "e551",
  "ins 551",
  "silica",
  "silicon dioxide"
 ],
 "ins 554": [
  "e554",
  "ins 554",
  "sodium aluminosilicate"
 ],
 "ins 621": [
  "ajinomoto",
  "e621",
  "flavour enhancer 621",
  "ins 621",
  "monosodium glutamate",
  "msg",
  "taste maker"
 ],
 "ins 627": [
  "disodium guanylate",
  "e627",
  "ins 627"
 ],
 "ins 631": [
  "disodium inosinate",
  "e631",
  "ins 631"
 ],
 "ins 635": [
  "disodium ribonucleotides",
  "e635",
  "ins 635"
 ],
 "ins 904": [
  "confectioners glaze",
  "e904",
  "ins 904",
  "shellac"
 ],
 "ins 924": [
  "bromate",
  "e924",
  "ins 924",
  "potassium bromate"
 ],
 "ins 950": [
  "ace k",
  "acesulfame k",
  "acesulfame potassium",
  "e950",
  "ins 950"
 ],
 "ins 951": [
  "aspartame",
  "e951",
  "ins 951"
 ],
 "ins 954": [
  "e954",
  "ins 954",
  "saccharin"
 ],
 "ins 955": [
  "e955",
  "ins 955",
  "sucralose"
 ],
 "ins 960": [
  "e960",
  "ins 960",
  "stevia",
  "steviol glycosides"
 ],
 "ins 961": [
  "e961",
  "ins 961",
  "neotame"
 ],
 "ins 965": [
  "e965",
  "ins 965",
  "maltitol"
 ],
 "ins 967": [
  "e967",
  "ins 967",
  "xylitol"
 ],
 "ins 968": [
  "e968",
  "erythritol",
  "ins 968"
 ],
 "instant coffee": [
  "coffee",
  "coffee extract",
  "coffee powder",
  "espresso",
  "instant coffee"
 ],
 "interesterified fat": [
  "interesterified fat",
  "interesterified vegetable fat"
 ],
 "interesterified vegetable fat": [
  "interesterified fat",
  "interesterified vegetable fat"
 ],
 "inulin": [
  "chicory inulin",
  "chicory root fibre",
  "fos",
  "fructooligosaccharide",
  "inulin"
 ],
 "invert sugar syrup": [
  "invert sugar",
  "invert sugar syrup",
  "invert syrup"
 ],
 "invert sugar": [
  "invert sugar",
  "invert sugar syrup",
  "invert syrup"
 ],
 "invert syrup": [
  "invert sugar",
  "invert sugar syrup",
  "invert syrup"
 ],
 "iodised salt": [
  "common salt",
  "iodised salt",
  "iodized salt",
  "namak",
  "salt",
  "table salt"
 ],
 "iodized salt": [
  "common salt",
  "iodised salt",
  "iodized salt",
  "namak",
  "salt",
  "table salt"
 ],
 "jaggery": [
  "cane jaggery",
  "gud",
  "gur",
  "jaggery"
 ],
 "jai": [
  "jai",
  "oat flour",
  "oat milk",
  "oatmeal",
  "oats",
  "rolled oats",
  "steel cut oats"
 ],
 "jau": [
  "barley",
  "jau",
  "pearl barley"
 ],
 "jhinga": [
  "crab",
  "crustacean",
  "crustacean shellfish",
  "jhinga",
  "krill",
  "lobster",
  "prawn",
  "shellfish",
  "shrimp"
 ],
 "jimikand": [
  "jimikand",
  "suran",
  "yam"
 ],
 "jowar flour": [
  "jowar",
  "jowar flour",
  "sorghum"
 ],
 "jowar": [
  "jowar",
  "jowar flour",
  "sorghum"
 ],
 "kabuli chana": [
  "besan",
  "chana",
  "chana dal",
  "chickpea",
  "gram flour",
  "kabuli chana"
 ],
 "kachi ghani": [
  "kachi ghani",
  "mustard oil",
  "sarson ka tel"
 ],
 "kaddu ke beej": [
  "kaddu ke beej",
  "pepita",
  "pumpkin seeds"
 ],
 "kaju": [
  "akhrot",
  "almond",
  "almond butter",
  "almond milk",
  "badam",
  "brazil nut",
  "cashew",
  "cashew butter",
  "cashew nut",
  "chilgoza",
  "dry fruit",
  "dry fruits",
  "dryfruit",
  "dryfruits",
  "hazelnut",
  "kaju",
  "macadamia",
  "marzipan",
  "pecan",
  "pine nut",
  "pista",
  "pistachio",
  "tree nuts",
  "walnut"
 ],
 "kanda": [
  "dehydrated onion",
  "kanda",
  "onion",
  "onion powder",
  "pyaaz",
  "pyaz"
 ],
 "kangni": [
  "foxtail millet",
  "kangni",
  "navane"
 ],
 "kashmiri chilli": [
  "cayenne",
  "chili",
  "chilli",
  "chilli flakes",
  "chilli powder",
  "green chilli",
  "kashmiri chilli",
  "lal mirch",
  "mirchi",
  "red chilli",
  "red chilli powder"
 ],
 "kasundi": [
  "kasundi",
  "mustard",
  "mustard seeds",
  "rai",
  "sarson"
 ],
 "khajur syrup": [
  "date paste",
  "date syrup",
  "khajur syrup"
 ],
 "khajur": [
  "dates",
  "khajur",
  "medjool"
 ],
 "khoya": [
  "butter",
  "buttermilk",
  "chaas",
  "cheese",
  "chhena",
  "cream",
  "curd",
  "dahi",
  "dairy",
  "khoya",
  "lactose",
  "makhan",
  "malai",
  "mawa",
  "milk",
  "milk fat",
  "milk powder",
  "milk solids",
  "milkfat",
  "paneer",
  "skimmed milk powder",
  "smp",
  "yoghurt",
  "yogurt"
 ],
 "kodo millet": [
  "kodo millet",
  "kodra",
  "varagu"
 ],
 "kodra": [
  "kodo millet",
  "kodra",
  "varagu"
 ],
 "krill": [
  "crab",
  "crustacean",
  "crustacean shellfish",
  "jhinga",
  "krill",
  "lobster",
  "prawn",
  "shellfish",
  "shrimp"
 ],
 "kuttu atta": [
  "buckwheat",
  "kuttu",
  "kuttu atta"
 ],
 "kuttu": [
  "buckwheat",
  "kuttu",
  "kuttu atta"
 ],
 "lactic acid": [
  "e270",
  "ins 270",
  "lactic acid"
 ],
 "lactobacillus": [
  "bifidobacterium",
  "dahi culture",
  "lactobacillus",
  "live cultures",
  "probiotic cultures",
  "yoghurt culture",
  "yoghurt cultures"
 ],
 "lactose": [
  "butter",
  "buttermilk",
  "chaas",
  "cheese",
  "chhena",
  "cream",
  "curd",
  "dahi",
  "dairy",
  "khoya",
  "lactose",
  "makhan",
  "malai",
  "mawa",
  "milk",
  "milk fat",
  "milk powder",
  "milk solids",
  "milkfat",
  "paneer",
  "skimmed milk powder",
  "smp",
  "yoghurt",
  "yogurt"
 ],
 "lahsun": [
  "garlic",
  "garlic powder",
  "lahsun",
  "lehsun"
 ],
 "lal mirch": [
  "cayenne",
  "chili",
  "chilli",
  "chilli flakes",
  "chilli powder",
  "green chilli",
  "kashmiri chilli",
  "lal mirch",
  "mirchi",
  "red chilli",
  "red chilli powder"
 ],
 "lecithin": [
  "e322",
  "ins 322",
  "lecithin",
  "soy lecithin",
  "soya lecithin"
 ],
 "lehsun": [
  "garlic",
  "garlic powder",
  "lahsun",
  "lehsun"
 ],
 "lentil": [
  "arhar",
  "daal",
  "dal",
  "dhal",
  "lentil",
  "lentils",
  "masoor",
  "moong",
  "pulse",
  "toor",
  "urad"
 ],
 "lentils": [
  "arhar",
  "daal",
  "dal",
  "dhal",
  "lentil",
  "lentils",
  "masoor",
  "moong",
  "pulse",
  "toor",
  "urad"
 ],
 "linseed": [
  "alsi",
  "flax seeds",
  "flaxseed",
  "linseed"
 ],
 "liquid egg": [
  "albumen",
  "albumin",
  "anda",
  "egg",
  "egg powder",
  "egg white",
  "egg yolk",
  "liquid egg"
 ],
 "liquid glucose": [
  "dextrose",
  "dextrose monohydrate",
  "glucose",
  "glucose syrup",
  "liquid glucose"
 ],
 "live cultures": [
  "bifidobacterium",
  "dahi culture",
  "lactobacillus",
  "live cultures",
  "probiotic cultures",
  "yoghurt culture",
  "yoghurt cultures"
 ],
 "lobster": [
  "crab",
  "crustacean",
  "crustacean shellfish",
  "jhinga",
  "krill",
  "lobster",
  "prawn",
  "shellfish",
  "shrimp"
 ],
 "locust bean gum": [
  "carob gum",
  "e410",
  "ins 410",
  "locust bean gum"
 ],
 "lotus seed": [
  "fox nut",
  "lotus seed",
  "makhana",
  "phool makhana"
 ],
 "low sodium salt": [
  "e508",
  "ins 508",
  "low sodium salt",
  "potassium chloride"
 ],
 "luo han guo": [
  "luo han guo",
  "mogroside",
  "monk fruit",
  "monk fruit extract"
 ],
 "lysozyme": [
  "e1105",
  "ins 1105",
  "lysozyme"
 ],
 "macadamia": [
  "akhrot",
  "almond",
  "almond butter",
  "almond milk",
  "badam",
  "brazil nut",
  "cashew",
  "cashew butter",
  "cashew nut",
  "chilgoza",
  "dry fruit",
  "dry fruits",
  "dryfruit",
  "dryfruits",
  "hazelnut",
  "kaju",
  "macadamia",
  "marzipan",
  "pecan",
  "pine nut",
  "pista",
  "pistachio",
  "tree nuts",
  "walnut"
 ],
 "machhli": [
  "anchovy",
  "fish",
  "fish oil",
  "fish sauce",
  "machhli",
  "machli",
  "salmon",
  "sardine",
  "tuna"
 ],
 "machli": [
  "anchovy",
  "fish",
  "fish oil",
  "fish sauce",
  "machhli",
  "machli",
  "salmon",
  "sardine",
  "tuna"
 ],
 "madhu": [
  "honey",
  "madhu",
  "shahad"
 ],
 "maida": [
  "all purpose flour",
  "apf",
  "maida",
  "refined flour",
  "refined wheat flour",
  "white flour"
 ],
 "maize starch": [
  "corn flour",
  "corn starch",
  "cornflour",
  "maize starch",
  "makai starch"
 ],
 "makai starch": [
  "corn flour",
  "corn starch",
  "cornflour",
  "maize starch",
  "makai starch"
 ],
 "makhan": [
  "butter",
  "buttermilk",
  "chaas",
  "cheese",
  "chhena",
  "cream",
  "curd",
  "dahi",
  "dairy",
  "khoya",
  "lactose",
  "makhan",
  "malai",
  "mawa",
  "milk",
  "milk fat",
  "milk powder",
  "milk solids",
  "milkfat",
  "paneer",
  "skimmed milk powder",
  "smp",
  "yoghurt",
  "yogurt"
 ],
 "makhana": [
  "fox nut",
  "lotus seed",
  "makhana",
  "phool makhana"
 ],
 "malai": [
  "butter",
  "buttermilk",
  "chaas",
  "cheese",
  "chhena",
  "cream",
  "curd",
  "dahi",
  "dairy",
  "khoya",
  "lactose",
  "makhan",
  "malai",
  "mawa",
  "milk",
  "milk fat",
  "milk powder",
  "milk solids",
  "milkfat",
  "paneer",
  "skimmed milk powder",
  "smp",
  "yoghurt",
  "yogurt"
 ],
 "malic acid": [
  "e296",
  "ins 296",
  "malic acid"
 ],
 "malt extract": [
  "cereals containing gluten",
  "gluten",
  "malt",
  "malt extract",
  "malted",
  "malted barley",
  "rye",
  "triticale",
  "vital gluten",
  "wheat gluten"
 ],
 "malt": [
  "cereals containing gluten",
  "gluten",
  "malt",
  "malt extract",
  "malted",
  "malted barley",
  "rye",
  "triticale",
  "vital gluten",
  "wheat gluten"
 ],
 "malted barley": [
  "cereals containing gluten",
  "gluten",
  "malt",
  "malt extract",
  "malted",
  "malted barley",
  "rye",
  "triticale",
  "vital gluten",
  "wheat gluten"
 ],
 "malted": [
  "cereals containing gluten",
  "gluten",
  "malt",
  "malt extract",
  "malted",
  "malted barley",
  "rye",
  "triticale",
  "vital gluten",
  "wheat gluten"
 ],
 "maltitol": [
  "e965",
  "ins 965",
  "maltitol"
 ],
 "marzipan": [
  "akhrot",
  "almond",
  "almond butter",
  "almond milk",
  "badam",
  "brazil nut",
  "cashew",
  "cashew butter",
  "cashew nut",
  "chilgoza",
  "dry fruit",
  "dry fruits",
  "dryfruit",
  "dryfruits",
  "hazelnut",
  "kaju",
  "macadamia",
  "marzipan",
  "pecan",
  "pine nut",
  "pista",
  "pistachio",
  "tree nuts",
  "walnut"
 ],
 "masoor": [
  "arhar",
  "daal",
  "dal",
  "dhal",
  "lentil",
  "lentils",
  "masoor",
  "moong",
  "pulse",
  "toor",
  "urad"
 ],
 "mawa": [
  "butter",
  "buttermilk",
  "chaas",
  "cheese",
  "chhena",
  "cream",
  "curd",
  "dahi",
  "dairy",
  "khoya",
  "lactose",
  "makhan",
  "malai",
  "mawa",
  "milk",
  "milk fat",
  "milk powder",
  "milk solids",
  "milkfat",
  "paneer",
  "skimmed milk powder",
  "smp",
  "yoghurt",
  "yogurt"
 ],
 "meat extract": [
  "meat",
  "meat extract"
 ],
 "meat": [
  "meat",
  "meat extract"
 ],
 "medjool": [
  "dates",
  "khajur",
  "medjool"
 ],
 "metabisulphite": [
  "e223",
  "ins 223",
  "metabisulphite",
  "sodium metabisulfite",
  "sodium metabisulphite"
 ],
 "milk fat": [
  "butter",
  "buttermilk",
  "chaas",
  "cheese",
  "chhena",
  "cream",
  "curd",
  "dahi",
  "dairy",
  "khoya",
  "lactose",
  "makhan",
  "malai",
  "mawa",
  "milk",
  "milk fat",
  "milk powder",
  "milk solids",
  "milkfat",
  "paneer",
  "skimmed milk powder",
  "smp",
  "yoghurt",
  "yogurt"
 ],
 "milk powder": [
  "butter",
  "buttermilk",
  "chaas",
  "cheese",
  "chhena",
  "cream",
  "curd",
  "dahi",
  "dairy",
  "khoya",
  "lactose",
  "makhan",
  "malai",
  "mawa",
  "milk",
  "milk fat",
  "milk powder",
  "milk solids",
  "milkfat",
  "paneer",
  "skimmed milk powder",
  "smp",
  "yoghurt",
  "yogurt"
 ],
 "milk protein": [
  "calcium caseinate",
  "casein",
  "caseinate",
  "milk protein",
  "sodium caseinate"
 ],
 "milk solids": [
  "butter",
  "buttermilk",
  "chaas",
  "cheese",
  "chhena",
  "cream",
  "curd",
  "dahi",
  "dairy",
  "khoya",
  "lactose",
  "makhan",
  "malai",
  "mawa",
  "milk",
  "milk fat",
  "milk powder",
  "milk solids",
  "milkfat",
  "paneer",
  "skimmed milk powder",
  "smp",
  "yoghurt",
  "yogurt"
 ],
 "milk": [
  "butter",
  "buttermilk",
  "chaas",
  "cheese",
  "chhena",
  "cream",
  "curd",
  "dahi",
  "dairy",
  "khoya",
  "lactose",
  "makhan",
  "malai",
  "mawa",
  "milk",
  "milk fat",
  "milk powder",
  "milk solids",
  "milkfat",
  "paneer",
  "skimmed milk powder",
  "smp",
  "yoghurt",
  "yogurt"
 ],
 "milkfat": [
  "butter",
  "buttermilk",
  "chaas",
  "cheese",
  "chhena",
  "cream",
  "curd",
  "dahi",
  "dairy",
  "khoya",
  "lactose",
  "makhan",
  "malai",
  "mawa",
  "milk",
  "milk fat",
  "milk powder",
  "milk solids",
  "milkfat",
  "paneer",
  "skimmed milk powder",
  "smp",
  "yoghurt",
  "yogurt"
 ],
 "mirchi": [
  "cayenne",
  "chili",
  "chilli",
  "chilli flakes",
  "chilli powder",
  "green chilli",
  "kashmiri chilli",
  "lal mirch",
  "mirchi",
  "red chilli",
  "red chilli powder"
 ],
 "mixed tocopherols": [
  "e306",
  "e307",
  "ins 306",
  "ins 307",
  "mixed tocopherols",
  "tocopherol",
  "tocopherols",
  "vitamin e"
 ],
 "modified corn starch": [
  "acetylated distarch adipate",
  "e1422",
  "ins 1422",
  "modified corn starch",
  "modified starch"
 ],
 "modified starch": [
  "acetylated distarch adipate",
  "e1422",
  "ins 1422",
  "modified corn starch",
  "modified starch"
 ],
 "mogroside": [
  "luo han guo",
  "mogroside",
  "monk fruit",
  "monk fruit extract"
 ],
 "monk fruit extract": [
  "luo han guo",
  "mogroside",
  "monk fruit",
  "monk fruit extract"
 ],
 "monk fruit": [
  "luo han guo",
  "mogroside",
  "monk fruit",
  "monk fruit extract"
 ],
 "mono and diglycerides": [
  "diglycerides",
  "e471",
  "ins 471",
  "mono and diglycerides",
  "mono- and diglycerides",
  "monoglycerides"
 ],
 "mono- and diglycerides": [
  "diglycerides",
  "e471",
  "ins 471",
  "mono and diglycerides",
  "mono- and diglycerides",
  "monoglycerides"
 ],
 "monoglycerides": [
  "diglycerides",
  "e471",
  "ins 471",
  "mono and diglycerides",
  "mono- and diglycerides",
  "monoglycerides"
 ],
 "monosodium glutamate": [
  "ajinomoto",
  "e621",
  "flavour enhancer 621",
  "ins 621",
  "monosodium glutamate",
  "msg",
  "taste maker"
 ],
 "mooli": [
  "mooli",
  "radish"
 ],
 "moong": [
  "arhar",
  "daal",
  "dal",
  "dhal",
  "lentil",
  "lentils",
  "masoor",
  "moong",
  "pulse",
  "toor",
  "urad"
 ],
 "moongfali": [
  "groundnut",
  "moongfali",
  "moongphali",
  "mungfali",
  "peanut",
  "peanut butter",
  "peanuts",
  "shengdana",
  "singdana"
 ],
 "moongphali": [
  "groundnut",
  "moongfali",
  "moongphali",
  "mungfali",
  "peanut",
  "peanut butter",
  "peanuts",
  "shengdana",
  "singdana"
 ],
 "moringa oleifera": [
  "drumstick leaf",
  "moringa",
  "moringa oleifera",
  "sahjan"
 ],
 "moringa": [
  "drumstick leaf",
  "moringa",
  "moringa oleifera",
  "sahjan"
 ],
 "msg": [
  "ajinomoto",
  "e621",
  "flavour enhancer 621",
  "ins 621",
  "monosodium glutamate",
  "msg",
  "taste maker"
 ],
 "mungfali": [
  "groundnut",
  "moongfali",
  "moongphali",
  "mungfali",
  "peanut",
  "peanut butter",
  "peanuts",
  "shengdana",
  "singdana"
 ],
 "mustard oil": [
  "kachi ghani",
  "mustard oil",
  "sarson ka tel"
 ],
 "mustard seeds": [
  "kasundi",
  "mustard",
  "mustard seeds",
  "rai",
  "sarson"
 ],
 "mustard": [
  "kasundi",
  "mustard",
  "mustard seeds",
  "rai",
  "sarson"
 ],
 "mutton": [
  "goat meat",
  "mutton"
 ],
 "nachni": [
  "finger millet",
  "nachni",
  "ragi",
  "ragi flour"
 ],
 "namak": [
  "common salt",
  "iodised salt",
  "iodized salt",
  "namak",
  "salt",
  "table salt"
 ],
 "nariyal tel": [
  "coconut oil",
  "nariyal tel",
  "virgin coconut oil"
 ],
 "natamycin": [
  "e235",
  "ins 235",
  "natamycin",
  "pimaricin"
 ],
 "nature identical flavoring substances": [
  "nature identical flavoring substances",
  "nature identical flavour",
  "nature identical flavouring",
  "nature identical flavouring substances",
  "nature identical flavours"
 ],
 "nature identical flavour": [
  "nature identical flavoring substances",
  "nature identical flavour",
  "nature identical flavouring",
  "nature identical flavouring substances",
  "nature identical flavours"
 ],
 "nature identical flavouring substances": [
  "nature identical flavoring substances",
  "nature identical flavour",
  "nature identical flavouring",
  "nature identical flavouring substances",
  "nature identical flavours"
 ],
 "nature identical flavouring": [
  "nature identical flavoring substances",
  "nature identical flavour",
  "nature identical flavouring",
  "nature identical flavouring substances",
  "nature identical flavours"
 ],
 "nature identical flavours": [
  "nature identical flavoring substances",
  "nature identical flavour",
  "nature identical flavouring",
  "nature identical flavouring substances",
  "nature identical flavours"
 ],
 "navane": [
  "foxtail millet",
  "kangni",
  "navane"
 ],
 "neotame": [
  "e961",
  "ins 961",
  "neotame"
 ],
 "nisin": [
  "e234",
  "ins 234",
  "nisin"
 ],
 "nitrate": [
  "e251",
  "ins 251",
  "nitrate",
  "sodium nitrate"
 ],
 "nitrite": [
  "e250",
  "ins 250",
  "nitrite",
  "sodium nitrite"
 ],
 "norbixin": [
  "annatto",
  "bixin",
  "e160b",
  "ins 160b",
  "norbixin"
 ],
 "oat flour": [
  "jai",
  "oat flour",
  "oat milk",
  "oatmeal",
  "oats",
  "rolled oats",
  "steel cut oats"
 ],
 "oat milk": [
  "jai",
  "oat flour",
  "oat milk",
  "oatmeal",
  "oats",
  "rolled oats",
  "steel cut oats"
 ],
 "oatmeal": [
  "jai",
  "oat flour",
  "oat milk",
  "oatmeal",
  "oats",
  "rolled oats",
  "steel cut oats"
 ],
 "oats": [
  "jai",
  "oat flour",
  "oat milk",
  "oatmeal",
  "oats",
  "rolled oats",
  "steel cut oats"
 ],
 "olive oil": [
  "evoo",
  "extra virgin olive oil",
  "olive oil"
 ],
 "onion powder": [
  "dehydrated onion",
  "kanda",
  "onion",
  "onion powder",
  "pyaaz",
  "pyaz"
 ],
 "onion": [
  "dehydrated onion",
  "kanda",
  "onion",
  "onion powder",
  "pyaaz",
  "pyaz"
 ],
 "palm fat": [
  "palm fat",
  "palm kernel oil",
  "palm oil",
  "palmolein",
  "refined palmolein",
  "vegetable fat palm"
 ],
 "palm kernel oil": [
  "palm fat",
  "palm kernel oil",
  "palm oil",
  "palmolein",
  "refined palmolein",
  "vegetable fat palm"
 ],
 "palm oil": [
  "palm fat",
  "palm kernel oil",
  "palm oil",
  "palmolein",
  "refined palmolein",
  "vegetable fat palm"
 ],
 "palmolein": [
  "palm fat",
  "palm kernel oil",
  "palm oil",
  "palmolein",
  "refined palmolein",
  "vegetable fat palm"
 ],
 "paneer": [
  "butter",
  "buttermilk",
  "chaas",
  "cheese",
  "chhena",
  "cream",
  "curd",
  "dahi",
  "dairy",
  "khoya",
  "lactose",
  "makhan",
  "malai",
  "mawa",
  "milk",
  "milk fat",
  "milk powder",
  "milk solids",
  "milkfat",
  "paneer",
  "skimmed milk powder",
  "smp",
  "yoghurt",
  "yogurt"
 ],
 "paprika extract": [
  "e160c",
  "ins 160c",
  "paprika extract",
  "paprika oleoresin"
 ],
 "paprika oleoresin": [
  "e160c",
  "ins 160c",
  "paprika extract",
  "paprika oleoresin"
 ],
 "partially hydrogenated oil": [
  "hydrogenated vegetable fat",
  "partially hydrogenated oil",
  "partially hydrogenated vegetable oil",
  "phvo"
 ],
 "partially hydrogenated vegetable oil": [
  "hydrogenated vegetable fat",
  "partially hydrogenated oil",
  "partially hydrogenated vegetable oil",
  "phvo"
 ],
 "pasta": [
  "bread",
  "bread crumbs",
  "breadcrumbs",
  "couscous",
  "durum",
  "pasta",
  "rava",
  "semolina",
  "suji",
  "wheat",
  "wheat flour",
  "whole wheat",
  "wholewheat"
 ],
 "peanut butter": [
  "groundnut",
  "moongfali",
  "moongphali",
  "mungfali",
  "peanut",
  "peanut butter",
  "peanuts",
  "shengdana",
  "singdana"
 ],
 "peanut oil": [
  "arachis oil",
  "groundnut oil",
  "peanut oil"
 ],
 "peanut": [
  "groundnut",
  "moongfali",
  "moongphali",
  "mungfali",
  "peanut",
  "peanut butter",
  "peanuts",
  "shengdana",
  "singdana"
 ],
 "peanuts": [
  "groundnut",
  "moongfali",
  "moongphali",
  "mungfali",
  "peanut",
  "peanut butter",
  "peanuts",
  "shengdana",
  "singdana"
 ],
 "pearl barley": [
  "barley",
  "jau",
  "pearl barley"
 ],
 "pearl millet": [
  "bajra",
  "bajra flour",
  "pearl millet"
 ],
 "pecan": [
  "akhrot",
  "almond",
  "almond butter",
  "almond milk",
  "badam",
  "brazil nut",
  "cashew",
  "cashew butter",
  "cashew nut",
  "chilgoza",
  "dry fruit",
  "dry fruits",
  "dryfruit",
  "dryfruits",
  "hazelnut",
  "kaju",
  "macadamia",
  "marzipan",
  "pecan",
  "pine nut",
  "pista",
  "pistachio",
  "tree nuts",
  "walnut"
 ],
 "pectin": [
  "e440",
  "ins 440",
  "pectin"
 ],
 "pepita": [
  "kaddu ke beej",
  "pepita",
  "pumpkin seeds"
 ],
 "phool makhana": [
  "fox nut",
  "lotus seed",
  "makhana",
  "phool makhana"
 ],
 "phosphoric acid": [
  "e338",
  "ins 338",
  "phosphoric acid"
 ],
 "phvo": [
  "hydrogenated vegetable fat",
  "partially hydrogenated oil",
  "partially hydrogenated vegetable oil",
  "phvo"
 ],
 "pimaricin": [
  "e235",
  "ins 235",
  "natamycin",
  "pimaricin"
 ],
 "pine nut": [
  "akhrot",
  "almond",
  "almond butter",
  "almond milk",
  "badam",
  "brazil nut",
  "cashew",
  "cashew butter",
  "cashew nut",
  "chilgoza",
  "dry fruit",
  "dry fruits",
  "dryfruit",
  "dryfruits",
  "hazelnut",
  "kaju",
  "macadamia",
  "marzipan",
  "pecan",
  "pine nut",
  "pista",
  "pistachio",
  "tree nuts",
  "walnut"
 ],
 "pink salt": [
  "himalayan salt",
  "pink salt",
  "rock salt",
  "sendha namak"
 ],
 "pista": [
  "akhrot",
  "almond",
  "almond butter",
  "almond milk",
  "badam",
  "brazil nut",
  "cashew",
  "cashew butter",
  "cashew nut",
  "chilgoza",
  "dry fruit",
  "dry fruits",
  "dryfruit",
  "dryfruits",
  "hazelnut",
  "kaju",
  "macadamia",
  "marzipan",
  "pecan",
  "pine nut",
  "pista",
  "pistachio",
  "tree nuts",
  "walnut"
 ],
 "pistachio": [
  "akhrot",
  "almond",
  "almond butter",
  "almond milk",
  "badam",
  "brazil nut",
  "cashew",
  "cashew butter",
  "cashew nut",
  "chilgoza",
  "dry fruit",
  "dry fruits",
  "dryfruit",
  "dryfruits",
  "hazelnut",
  "kaju",
  "macadamia",
  "marzipan",
  "pecan",
  "pine nut",
  "pista",
  "pistachio",
  "tree nuts",
  "walnut"
 ],
 "polished rice": [
  "basmati rice",
  "chaval",
  "chawal",
  "polished rice",
  "white rice"
 ],
 "polyphosphate": [
  "e452",
  "ins 452",
  "polyphosphate",
  "polyphosphates",
  "sodium polyphosphate"
 ],
 "polyphosphates": [
  "e452",
  "ins 452",
  "polyphosphate",
  "polyphosphates",
  "sodium polyphosphate"
 ],
 "polysorbate 80": [
  "e433",
  "ins 433",
  "polysorbate 80",
  "tween 80"
 ],
 "ponceau 4r": [
  "cochineal red a",
  "e124",
  "ins 124",
  "ponceau 4r"
 ],
 "pork": [
  "bacon",
  "ham",
  "pork"
 ],
 "potassium bromate": [
  "bromate",
  "e924",
  "ins 924",
  "potassium bromate"
 ],
 "potassium chloride": [
  "e508",
  "ins 508",
  "low sodium salt",
  "potassium chloride"
 ],
 "potassium metabisulphite": [
  "e224",
  "ins 224",
  "potassium metabisulphite"
 ],
 "potassium sorbate": [
  "e202",
  "ins 202",
  "potassium sorbate"
 ],
 "potato flakes": [
  "aloo",
  "dehydrated potato",
  "potato",
  "potato flakes",
  "potato powder"
 ],
 "potato flour": [
  "potato flour",
  "potato starch"
 ],
 "potato powder": [
  "aloo",
  "dehydrated potato",
  "potato",
  "potato flakes",
  "potato powder"
 ],
 "potato starch": [
  "potato flour",
  "potato starch"
 ],
 "potato": [
  "aloo",
  "dehydrated potato",
  "potato",
  "potato flakes",
  "potato powder"
 ],
 "prawn": [
  "crab",
  "crustacean",
  "crustacean shellfish",
  "jhinga",
  "krill",
  "lobster",
  "prawn",
  "shellfish",
  "shrimp"
 ],
 "probiotic cultures": [
  "bifidobacterium",
  "dahi culture",
  "lactobacillus",
  "live cultures",
  "probiotic cultures",
  "yoghurt culture",
  "yoghurt cultures"
 ],
 "pulse": [
  "arhar",
  "daal",
  "dal",
  "dhal",
  "lentil",
  "lentils",
  "masoor",
  "moong",
  "pulse",
  "toor",
  "urad"
 ],
 "pumpkin seeds": [
  "kaddu ke beej",
  "pepita",
  "pumpkin seeds"
 ],
 "pyaaz": [
  "dehydrated onion",
  "kanda",
  "onion",
  "onion powder",
  "pyaaz",
  "pyaz"
 ],
 "pyaz": [
  "dehydrated onion",
  "kanda",
  "onion",
  "onion powder",
  "pyaaz",
  "pyaz"
 ],
 "quinoline yellow": [
  "e104",
  "ins 104",
  "quinoline yellow"
 ],
 "radish": [
  "mooli",
  "radish"
 ],
 "ragi flour": [
  "finger millet",
  "nachni",
  "ragi",
  "ragi flour"
 ],
 "ragi": [
  "finger millet",
  "nachni",
  "ragi",
  "ragi flour"
 ],
 "rai": [
  "kasundi",
  "mustard",
  "mustard seeds",
  "rai",
  "sarson"
 ],
 "rajgira": [
  "amaranth",
  "rajgira",
  "ramdana"
 ],
 "ramdana": [
  "amaranth",
  "rajgira",
  "ramdana"
 ],
 "rapeseed oil": [
  "canola",
  "canola oil",
  "rapeseed oil"
 ],
 "rava": [
  "bread",
  "bread crumbs",
  "breadcrumbs",
  "couscous",
  "durum",
  "pasta",
  "rava",
  "semolina",
  "suji",
  "wheat",
  "wheat flour",
  "whole wheat",
  "wholewheat"
 ],
 "red 3": [
  "e127",
  "erythrosine",
  "fd c red 3",
  "ins 127",
  "red 3"
 ],
 "red 40": [
  "allura red",
  "allura red ac",
  "e129",
  "fd c red 40",
  "ins 129",
  "red 40"
 ],
 "red chilli powder": [
  "cayenne",
  "chili",
  "chilli",
  "chilli flakes",
  "chilli powder",
  "green chilli",
  "kashmiri chilli",
  "lal mirch",
  "mirchi",
  "red chilli",
  "red chilli powder"
 ],
 "red chilli": [
  "cayenne",
  "chili",
  "chilli",
  "chilli flakes",
  "chilli powder",
  "green chilli",
  "kashmiri chilli",
  "lal mirch",
  "mirchi",
  "red chilli",
  "red chilli powder"
 ],
 "refined flour": [
  "all purpose flour",
  "apf",
  "maida",
  "refined flour",
  "refined wheat flour",
  "white flour"
 ],
 "refined palmolein": [
  "palm fat",
  "palm kernel oil",
  "palm oil",
  "palmolein",
  "refined palmolein",
  "vegetable fat palm"
 ],
 "refined sugar": [
  "cane sugar",
  "chini",
  "refined sugar",
  "sucrose",
  "sugar",
  "white sugar"
 ],
 "refined wheat flour": [
  "all purpose flour",
  "apf",
  "maida",
  "refined flour",
  "refined wheat flour",
  "white flour"
 ],
 "rice flour": [
  "chawal atta",
  "rice flour"
 ],
 "rock salt": [
  "himalayan salt",
  "pink salt",
  "rock salt",
  "sendha namak"
 ],
 "rolled oats": [
  "jai",
  "oat flour",
  "oat milk",
  "oatmeal",
  "oats",
  "rolled oats",
  "steel cut oats"
 ],
 "rye": [
  "cereals containing gluten",
  "gluten",
  "malt",
  "malt extract",
  "malted",
  "malted barley",
  "rye",
  "triticale",
  "vital gluten",
  "wheat gluten"
 ],
 "sabja substitute": [
  "chia",
  "chia seeds",
  "sabja substitute"
 ],
 "sabudana": [
  "cassava starch",
  "sabudana",
  "sago",
  "tapioca",
  "tapioca starch"
 ],
 "saccharin": [
  "e954",
  "ins 954",
  "saccharin"
 ],
 "sago": [
  "cassava starch",
  "sabudana",
  "sago",
  "tapioca",
  "tapioca starch"
 ],
 "sahjan": [
  "drumstick leaf",
  "moringa",
  "moringa oleifera",
  "sahjan"
 ],
 "salmon": [
  "anchovy",
  "fish",
  "fish oil",
  "fish sauce",
  "machhli",
  "machli",
  "salmon",
  "sardine",
  "tuna"
 ],
 "salt": [
  "common salt",
  "iodised salt",
  "iodized salt",
  "namak",
  "salt",
  "table salt"
 ],
 "sapp": [
  "diphosphate",
  "diphosphates",
  "e450",
  "ins 450",
  "sapp",
  "sodium acid pyrophosphate"
 ],
 "sardine": [
  "anchovy",
  "fish",
  "fish oil",
  "fish sauce",
  "machhli",
  "machli",
  "salmon",
  "sardine",
  "tuna"
 ],
 "sarson ka tel": [
  "kachi ghani",
  "mustard oil",
  "sarson ka tel"
 ],
 "sarson": [
  "kasundi",
  "mustard",
  "mustard seeds",
  "rai",
  "sarson"
 ],
 "semolina": [
  "bread",
  "bread crumbs",
  "breadcrumbs",
  "couscous",
  "durum",
  "pasta",
  "rava",
  "semolina",
  "suji",
  "wheat",
  "wheat flour",
  "whole wheat",
  "wholewheat"
 ],
 "sendha namak": [
  "himalayan salt",
  "pink salt",
  "rock salt",
  "sendha namak"
 ],
 "sesame oil": [
  "gingelly oil",
  "sesame oil",
  "til oil"
 ],
 "sesame seeds": [
  "gingelly",
  "sesame",
  "sesame seeds",
  "tahini",
  "til"
 ],
 "sesame": [
  "gingelly",
  "sesame",
  "sesame seeds",
  "tahini",
  "til"
 ],
 "shahad": [
  "honey",
  "madhu",
  "shahad"
 ],
 "shakarkandi": [
  "shakarkandi",
  "sweet potato"
 ],
 "shalgam": [
  "shalgam",
  "turnip"
 ],
 "shellac": [
  "confectioners glaze",
  "e904",
  "ins 904",
  "shellac"
 ],
 "shellfish": [
  "crab",
  "crustacean",
  "crustacean shellfish",
  "jhinga",
  "krill",
  "lobster",
  "prawn",
  "shellfish",
  "shrimp"
 ],
 "shengdana": [
  "groundnut",
  "moongfali",
  "moongphali",
  "mungfali",
  "peanut",
  "peanut butter",
  "peanuts",
  "shengdana",
  "singdana"
 ],
 "shrimp": [
  "crab",
  "crustacean",
  "crustacean shellfish",
  "jhinga",
  "krill",
  "lobster",
  "prawn",
  "shellfish",
  "shrimp"
 ],
 "silica": [
  "e551",
  "ins 551",
  "silica",
  "silicon dioxide"
 ],
 "silicon dioxide": [
  "e551",
  "ins 551",
  "silica",
  "silicon dioxide"
 ],
 "singdana": [
  "groundnut",
  "moongfali",
  "moongphali",
  "mungfali",
  "peanut",
  "peanut butter",
  "peanuts",
  "shengdana",
  "singdana"
 ],
 "skimmed milk powder": [
  "butter",
  "buttermilk",
  "chaas",
  "cheese",
  "chhena",
  "cream",
  "curd",
  "dahi",
  "dairy",
  "khoya",
  "lactose",
  "makhan",
  "malai",
  "mawa",
  "milk",
  "milk fat",
  "milk powder",
  "milk solids",
  "milkfat",
  "paneer",
  "skimmed milk powder",
  "smp",
  "yoghurt",
  "yogurt"
 ],
 "smp": [
  "butter",
  "buttermilk",
  "chaas",
  "cheese",
  "chhena",
  "cream",
  "curd",
  "dahi",
  "dairy",
  "khoya",
  "lactose",
  "makhan",
  "malai",
  "mawa",
  "milk",
  "milk fat",
  "milk powder",
  "milk solids",
  "milkfat",
  "paneer",
  "skimmed milk powder",
  "smp",
  "yoghurt",
  "yogurt"
 ],
 "sodium acid pyrophosphate": [
  "diphosphate",
  "diphosphates",
  "e450",
  "ins 450",
  "sapp",
  "sodium acid pyrophosphate"
 ],
 "sodium aluminium phosphate": [
  "e541",
  "ins 541",
  "sodium aluminium phosphate"
 ],
 "sodium aluminosilicate": [
  "e554",
  "ins 554",
  "sodium aluminosilicate"
 ],
 "sodium benzoate": [
  "benzoate",
  "e211",
  "ins 211",
  "sodium benzoate"
 ],
 "sodium bicarbonate": [
  "baking soda",
  "e500",
  "ins 500",
  "sodium bicarbonate"
 ],
 "sodium caseinate": [
  "calcium caseinate",
  "casein",
  "caseinate",
  "milk protein",
  "sodium caseinate"
 ],
 "sodium citrate": [
  "e331",
  "ins 331",
  "sodium citrate",
  "trisodium citrate"
 ],
 "sodium metabisulfite": [
  "e223",
  "ins 223",
  "metabisulphite",
  "sodium metabisulfite",
  "sodium metabisulphite"
 ],
 "sodium metabisulphite": [
  "e223",
  "ins 223",
  "metabisulphite",
  "sodium metabisulfite",
  "sodium metabisulphite"
 ],
 "sodium nitrate": [
  "e251",
  "ins 251",
  "nitrate",
  "sodium nitrate"
 ],
 "sodium nitrite": [
  "e250",
  "ins 250",
  "nitrite",
  "sodium nitrite"
 ],
 "sodium polyphosphate": [
  "e452",
  "ins 452",
  "polyphosphate",
  "polyphosphates",
  "sodium polyphosphate"
 ],
 "sonth": [
  "adrak",
  "dry ginger",
  "ginger",
  "ginger powder",
  "sonth"
 ],
 "sorbic acid": [
  "e200",
  "ins 200",
  "sorbic acid"
 ],
 "sorbitol": [
  "e420",
  "ins 420",
  "sorbitol"
 ],
 "sorghum": [
  "jowar",
  "jowar flour",
  "sorghum"
 ],
 "soy lecithin": [
  "e322",
  "ins 322",
  "lecithin",
  "soy lecithin",
  "soya lecithin"
 ],
 "soy milk": [
  "soy",
  "soy milk",
  "soy protein",
  "soya",
  "soya bean",
  "soya chunks",
  "soya flour",
  "soya milk",
  "soyabean",
  "soybean",
  "textured vegetable protein",
  "tofu",
  "tvp"
 ],
 "soy protein": [
  "soy",
  "soy milk",
  "soy protein",
  "soya",
  "soya bean",
  "soya chunks",
  "soya flour",
  "soya milk",
  "soyabean",
  "soybean",
  "textured vegetable protein",
  "tofu",
  "tvp"
 ],
 "soy": [
  "soy",
  "soy milk",
  "soy protein",
  "soya",
  "soya bean",
  "soya chunks",
  "soya flour",
  "soya milk",
  "soyabean",
  "soybean",
  "textured vegetable protein",
  "tofu",
  "tvp"
 ],
 "soya bean": [
  "soy",
  "soy milk",
  "soy protein",
  "soya",
  "soya bean",
  "soya chunks",
  "soya flour",
  "soya milk",
  "soyabean",
  "soybean",
  "textured vegetable protein",
  "tofu",
  "tvp"
 ],
 "soya chunks": [
  "soy",
  "soy milk",
  "soy protein",
  "soya",
  "soya bean",
  "soya chunks",
  "soya flour",
  "soya milk",
  "soyabean",
  "soybean",
  "textured vegetable protein",
  "tofu",
  "tvp"
 ],
 "soya flour": [
  "soy",
  "soy milk",
  "soy protein",
  "soya",
  "soya bean",
  "soya chunks",
  "soya flour",
  "soya milk",
  "soyabean",
  "soybean",
  "textured vegetable protein",
  "tofu",
  "tvp"
 ],
 "soya lecithin": [
  "e322",
  "ins 322",
  "lecithin",
  "soy lecithin",
  "soya lecithin"
 ],
 "soya milk": [
  "soy",
  "soy milk",
  "soy protein",
  "soya",
  "soya bean",
  "soya chunks",
  "soya flour",
  "soya milk",
  "soyabean",
  "soybean",
  "textured vegetable protein",
  "tofu",
  "tvp"
 ],
 "soya oil": [
  "soya oil",
  "soyabean oil",
  "soybean oil"
 ],
 "soya": [
  "soy",
  "soy milk",
  "soy protein",
  "soya",
  "soya bean",
  "soya chunks",
  "soya flour",
  "soya milk",
  "soyabean",
  "soybean",
  "textured vegetable protein",
  "tofu",
  "tvp"
 ],
 "soyabean oil": [
  "soya oil",
  "soyabean oil",
  "soybean oil"
 ],
 "soyabean": [
  "soy",
  "soy milk",
  "soy protein",
  "soya",
  "soya bean",
  "soya chunks",
  "soya flour",
  "soya milk",
  "soyabean",
  "soybean",
  "textured vegetable protein",
  "tofu",
  "tvp"
 ],
 "soybean oil": [
  "soya oil",
  "soyabean oil",
  "soybean oil"
 ],
 "soybean": [
  "soy",
  "soy milk",
  "soy protein",
  "soya",
  "soya bean",
  "soya chunks",
  "soya flour",
  "soya milk",
  "soyabean",
  "soybean",
  "textured vegetable protein",
  "tofu",
  "tvp"
 ],
 "steel cut oats": [
  "jai",
  "oat flour",
  "oat milk",
  "oatmeal",
  "oats",
  "rolled oats",
  "steel cut oats"
 ],
 "stevia": [
  "e960",
  "ins 960",
  "stevia",
  "steviol glycosides"
 ],
 "steviol glycosides": [
  "e960",
  "ins 960",
  "stevia",
  "steviol glycosides"
 ],
 "sucralose": [
  "e955",
  "ins 955",
  "sucralose"
 ],
 "sucrose": [
  "cane sugar",
  "chini",
  "refined sugar",
  "sucrose",
  "sugar",
  "white sugar"
 ],
 "sugar": [
  "cane sugar",
  "chini",
  "refined sugar",
  "sucrose",
  "sugar",
  "white sugar"
 ],
 "suji": [
  "bread",
  "bread crumbs",
  "breadcrumbs",
  "couscous",
  "durum",
  "pasta",
  "rava",
  "semolina",
  "suji",
  "wheat",
  "wheat flour",
  "whole wheat",
  "wholewheat"
 ],
 "sulfites": [
  "sulfites",
  "sulphites",
  "sulphites (declarable)",
  "sulphites declarable",
  "sulphiting agents"
 ],
 "sulfur dioxide": [
  "e220",
  "ins 220",
  "sulfur dioxide",
  "sulphur dioxide"
 ],
 "sulphites (declarable)": [
  "sulfites",
  "sulphites",
  "sulphites (declarable)",
  "sulphites declarable",
  "sulphiting agents"
 ],
 "sulphites declarable": [
  "sulfites",
  "sulphites",
  "sulphites (declarable)",
  "sulphites declarable",
  "sulphiting agents"
 ],
 "sulphites": [
  "sulfites",
  "sulphites",
  "sulphites (declarable)",
  "sulphites declarable",
  "sulphiting agents"
 ],
 "sulphiting agents": [
  "sulfites",
  "sulphites",
  "sulphites (declarable)",
  "sulphites declarable",
  "sulphiting agents"
 ],
 "sulphur dioxide": [
  "e220",
  "ins 220",
  "sulfur dioxide",
  "sulphur dioxide"
 ],
 "sunflower oil": [
  "sunflower oil",
  "sunflower seed oil"
 ],
 "sunflower seed oil": [
  "sunflower oil",
  "sunflower seed oil"
 ],
 "sunflower seeds": [
  "sunflower seeds",
  "surajmukhi ke beej"
 ],
 "sunset yellow fcf": [
  "e110",
  "fd c yellow 6",
  "ins 110",
  "sunset yellow",
  "sunset yellow fcf",
  "yellow 6"
 ],
 "sunset yellow": [
  "e110",
  "fd c yellow 6",
  "ins 110",
  "sunset yellow",
  "sunset yellow fcf",
  "yellow 6"
 ],
 "surajmukhi ke beej": [
  "sunflower seeds",
  "surajmukhi ke beej"
 ],
 "suran": [
  "jimikand",
  "suran",
  "yam"
 ],
 "sweet potato": [
  "shakarkandi",
  "sweet potato"
 ],
 "table salt": [
  "common salt",
  "iodised salt",
  "iodized salt",
  "namak",
  "salt",
  "table salt"
 ],
 "tahini": [
  "gingelly",
  "sesame",
  "sesame seeds",
  "tahini",
  "til"
 ],
 "tapioca starch": [
  "cassava starch",
  "sabudana",
  "sago",
  "tapioca",
  "tapioca starch"
 ],
 "tapioca": [
  "cassava starch",
  "sabudana",
  "sago",
  "tapioca",
  "tapioca starch"
 ],
 "taro": [
  "arbi",
  "colocasia",
  "taro"
 ],
 "tartrazine": [
  "e102",
  "fd c yellow 5",
  "ins 102",
  "tartrazine",
  "yellow 5"
 ],
 "taste maker": [
  "ajinomoto",
  "e621",
  "flavour enhancer 621",
  "ins 621",
  "monosodium glutamate",
  "msg",
  "taste maker"
 ],
 "tbhq": [
  "e319",
  "ins 319",
  "tbhq",
  "tertiary butylhydroquinone"
 ],
 "tea extract": [
  "black tea",
  "green tea",
  "green tea extract",
  "tea",
  "tea extract",
  "tea leaves",
  "tea powder"
 ],
 "tea leaves": [
  "black tea",
  "green tea",
  "green tea extract",
  "tea",
  "tea extract",
  "tea leaves",
  "tea powder"
 ],
 "tea powder": [
  "black tea",
  "green tea",
  "green tea extract",
  "tea",
  "tea extract",
  "tea leaves",
  "tea powder"
 ],
 "tea": [
  "black tea",
  "green tea",
  "green tea extract",
  "tea",
  "tea extract",
  "tea leaves",
  "tea powder"
 ],
 "tertiary butylhydroquinone": [
  "e319",
  "ins 319",
  "tbhq",
  "tertiary butylhydroquinone"
 ],
 "textured vegetable protein": [
  "soy",
  "soy milk",
  "soy protein",
  "soya",
  "soya bean",
  "soya chunks",
  "soya flour",
  "soya milk",
  "soyabean",
  "soybean",
  "textured vegetable protein",
  "tofu",
  "tvp"
 ],
 "til oil": [
  "gingelly oil",
  "sesame oil",
  "til oil"
 ],
 "til": [
  "gingelly",
  "sesame",
  "sesame seeds",
  "tahini",
  "til"
 ],
 "titanium dioxide": [
  "e171",
  "ins 171",
  "titanium dioxide"
 ],
 "tocopherol": [
  "e306",
  "e307",
  "ins 306",
  "ins 307",
  "mixed tocopherols",
  "tocopherol",
  "tocopherols",
  "vitamin e"
 ],
 "tocopherols": [
  "e306",
  "e307",
  "ins 306",
  "ins 307",
  "mixed tocopherols",
  "tocopherol",
  "tocopherols",
  "vitamin e"
 ],
 "tofu": [
  "soy",
  "soy milk",
  "soy protein",
  "soya",
  "soya bean",
  "soya chunks",
  "soya flour",
  "soya milk",
  "soyabean",
  "soybean",
  "textured vegetable protein",
  "tofu",
  "tvp"
 ],
 "toor": [
  "arhar",
  "daal",
  "dal",
  "dhal",
  "lentil",
  "lentils",
  "masoor",
  "moong",
  "pulse",
  "toor",
  "urad"
 ],
 "trans fat": [
  "industrial trans fat",
  "trans fat",
  "trans fatty acids"
 ],
 "trans fatty acids": [
  "industrial trans fat",
  "trans fat",
  "trans fatty acids"
 ],
 "tree nuts": [
  "akhrot",
  "almond",
  "almond butter",
  "almond milk",
  "badam",
  "brazil nut",
  "cashew",
  "cashew butter",
  "cashew nut",
  "chilgoza",
  "dry fruit",
  "dry fruits",
  "dryfruit",
  "dryfruits",
  "hazelnut",
  "kaju",
  "macadamia",
  "marzipan",
  "pecan",
  "pine nut",
  "pista",
  "pistachio",
  "tree nuts",
  "walnut"
 ],
 "trisodium citrate": [
  "e331",
  "ins 331",
  "sodium citrate",
  "trisodium citrate"
 ],
 "triticale": [
  "cereals containing gluten",
  "gluten",
  "malt",
  "malt extract",
  "malted",
  "malted barley",
  "rye",
  "triticale",
  "vital gluten",
  "wheat gluten"
 ],
 "tuna": [
  "anchovy",
  "fish",
  "fish oil",
  "fish sauce",
  "machhli",
  "machli",
  "salmon",
  "sardine",
  "tuna"
 ],
 "turmeric colour": [
  "curcumin",
  "e100",
  "ins 100",
  "turmeric colour"
 ],
 "turmeric": [
  "curcuma",
  "haldi",
  "turmeric"
 ],
 "turnip": [
  "shalgam",
  "turnip"
 ],
 "tvp": [
  "soy",
  "soy milk",
  "soy protein",
  "soya",
  "soya bean",
  "soya chunks",
  "soya flour",
  "soya milk",
  "soyabean",
  "soybean",
  "textured vegetable protein",
  "tofu",
  "tvp"
 ],
 "tween 80": [
  "e433",
  "ins 433",
  "polysorbate 80",
  "tween 80"
 ],
 "unpolished rice": [
  "brown rice",
  "unpolished rice"
 ],
 "urad": [
  "arhar",
  "daal",
  "dal",
  "dhal",
  "lentil",
  "lentils",
  "masoor",
  "moong",
  "pulse",
  "toor",
  "urad"
 ],
 "vanaspati ghee": [
  "dalda",
  "hydrogenated vegetable oil",
  "vanaspati",
  "vanaspati ghee",
  "vegetable ghee"
 ],
 "vanaspati": [
  "dalda",
  "hydrogenated vegetable oil",
  "vanaspati",
  "vanaspati ghee",
  "vegetable ghee"
 ],
 "varagu": [
  "kodo millet",
  "kodra",
  "varagu"
 ],
 "vegetable fat palm": [
  "palm fat",
  "palm kernel oil",
  "palm oil",
  "palmolein",
  "refined palmolein",
  "vegetable fat palm"
 ],
 "vegetable ghee": [
  "dalda",
  "hydrogenated vegetable oil",
  "vanaspati",
  "vanaspati ghee",
  "vegetable ghee"
 ],
 "vinegar": [
  "acetic acid",
  "e260",
  "ins 260",
  "vinegar"
 ],
 "virgin coconut oil": [
  "coconut oil",
  "nariyal tel",
  "virgin coconut oil"
 ],
 "vital gluten": [
  "cereals containing gluten",
  "gluten",
  "malt",
  "malt extract",
  "malted",
  "malted barley",
  "rye",
  "triticale",
  "vital gluten",
  "wheat gluten"
 ],
 "vitamin c": [
  "ascorbic acid",
  "e300",
  "ins 300",
  "vitamin c"
 ],
 "vitamin e": [
  "e306",
  "e307",
  "ins 306",
  "ins 307",
  "mixed tocopherols",
  "tocopherol",
  "tocopherols",
  "vitamin e"
 ],
 "walnut": [
  "akhrot",
  "almond",
  "almond butter",
  "almond milk",
  "badam",
  "brazil nut",
  "cashew",
  "cashew butter",
  "cashew nut",
  "chilgoza",
  "dry fruit",
  "dry fruits",
  "dryfruit",
  "dryfruits",
  "hazelnut",
  "kaju",
  "macadamia",
  "marzipan",
  "pecan",
  "pine nut",
  "pista",
  "pistachio",
  "tree nuts",
  "walnut"
 ],
 "wheat flour": [
  "bread",
  "bread crumbs",
  "breadcrumbs",
  "couscous",
  "durum",
  "pasta",
  "rava",
  "semolina",
  "suji",
  "wheat",
  "wheat flour",
  "whole wheat",
  "wholewheat"
 ],
 "wheat gluten": [
  "cereals containing gluten",
  "gluten",
  "malt",
  "malt extract",
  "malted",
  "malted barley",
  "rye",
  "triticale",
  "vital gluten",
  "wheat gluten"
 ],
 "wheat": [
  "bread",
  "bread crumbs",
  "breadcrumbs",
  "couscous",
  "durum",
  "pasta",
  "rava",
  "semolina",
  "suji",
  "wheat",
  "wheat flour",
  "whole wheat",
  "wholewheat"
 ],
 "whey permeate": [
  "whey",
  "whey permeate",
  "whey protein",
  "whey protein concentrate",
  "whey protein isolate",
  "wpc",
  "wpi"
 ],
 "whey protein concentrate": [
  "whey",
  "whey permeate",
  "whey protein",
  "whey protein concentrate",
  "whey protein isolate",
  "wpc",
  "wpi"
 ],
 "whey protein isolate": [
  "whey",
  "whey permeate",
  "whey protein",
  "whey protein concentrate",
  "whey protein isolate",
  "wpc",
  "wpi"
 ],
 "whey protein": [
  "whey",
  "whey permeate",
  "whey protein",
  "whey protein concentrate",
  "whey protein isolate",
  "wpc",
  "wpi"
 ],
 "whey": [
  "whey",
  "whey permeate",
  "whey protein",
  "whey protein concentrate",
  "whey protein isolate",
  "wpc",
  "wpi"
 ],
 "white flour": [
  "all purpose flour",
  "apf",
  "maida",
  "refined flour",
  "refined wheat flour",
  "white flour"
 ],
 "white rice": [
  "basmati rice",
  "chaval",
  "chawal",
  "polished rice",
  "white rice"
 ],
 "white sugar": [
  "cane sugar",
  "chini",
  "refined sugar",
  "sucrose",
  "sugar",
  "white sugar"
 ],
 "whole meal flour": [
  "aata",
  "aatta",
  "ata",
  "atta",
  "chakki atta",
  "gehun atta",
  "whole meal flour",
  "whole wheat flour",
  "wholewheat flour"
 ],
 "whole wheat flour": [
  "aata",
  "aatta",
  "ata",
  "atta",
  "chakki atta",
  "gehun atta",
  "whole meal flour",
  "whole wheat flour",
  "wholewheat flour"
 ],
 "whole wheat": [
  "bread",
  "bread crumbs",
  "breadcrumbs",
  "couscous",
  "durum",
  "pasta",
  "rava",
  "semolina",
  "suji",
  "wheat",
  "wheat flour",
  "whole wheat",
  "wholewheat"
 ],
 "wholewheat flour": [
  "aata",
  "aatta",
  "ata",
  "atta",
  "chakki atta",
  "gehun atta",
  "whole meal flour",
  "whole wheat flour",
  "wholewheat flour"
 ],
 "wholewheat": [
  "bread",
  "bread crumbs",
  "breadcrumbs",
  "couscous",
  "durum",
  "pasta",
  "rava",
  "semolina",
  "suji",
  "wheat",
  "wheat flour",
  "whole wheat",
  "wholewheat"
 ],
 "wpc": [
  "whey",
  "whey permeate",
  "whey protein",
  "whey protein concentrate",
  "whey protein isolate",
  "wpc",
  "wpi"
 ],
 "wpi": [
  "whey",
  "whey permeate",
  "whey protein",
  "whey protein concentrate",
  "whey protein isolate",
  "wpc",
  "wpi"
 ],
 "xanthan gum": [
  "e415",
  "ins 415",
  "xanthan gum"
 ],
 "xylitol": [
  "e967",
  "ins 967",
  "xylitol"
 ],
 "yam": [
  "jimikand",
  "suran",
  "yam"
 ],
 "yeast extract": [
  "autolysed yeast",
  "hvp",
  "hydrolysed vegetable protein",
  "yeast extract"
 ],
 "yellow 5": [
  "e102",
  "fd c yellow 5",
  "ins 102",
  "tartrazine",
  "yellow 5"
 ],
 "yellow 6": [
  "e110",
  "fd c yellow 6",
  "ins 110",
  "sunset yellow",
  "sunset yellow fcf",
  "yellow 6"
 ],
 "yoghurt culture": [
  "bifidobacterium",
  "dahi culture",
  "lactobacillus",
  "live cultures",
  "probiotic cultures",
  "yoghurt culture",
  "yoghurt cultures"
 ],
 "yoghurt cultures": [
  "bifidobacterium",
  "dahi culture",
  "lactobacillus",
  "live cultures",
  "probiotic cultures",
  "yoghurt culture",
  "yoghurt cultures"
 ],
 "yoghurt": [
  "butter",
  "buttermilk",
  "chaas",
  "cheese",
  "chhena",
  "cream",
  "curd",
  "dahi",
  "dairy",
  "khoya",
  "lactose",
  "makhan",
  "malai",
  "mawa",
  "milk",
  "milk fat",
  "milk powder",
  "milk solids",
  "milkfat",
  "paneer",
  "skimmed milk powder",
  "smp",
  "yoghurt",
  "yogurt"
 ],
 "yogurt": [
  "butter",
  "buttermilk",
  "chaas",
  "cheese",
  "chhena",
  "cream",
  "curd",
  "dahi",
  "dairy",
  "khoya",
  "lactose",
  "makhan",
  "malai",
  "mawa",
  "milk",
  "milk fat",
  "milk powder",
  "milk solids",
  "milkfat",
  "paneer",
  "skimmed milk powder",
  "smp",
  "yoghurt",
  "yogurt"
 ]
});

/** The shelf a word means, when it means a kind of food rather than a product. */
export const CATEGORY_WORDS = Object.freeze({
 "dry fruit": "nuts_seeds.dried_fruit",
 "dryfruit": "nuts_seeds.dried_fruit",
 "dry fruits": "nuts_seeds.dried_fruit",
 "dried fruits": "nuts_seeds.dried_fruit",
 "sukha meva": "nuts_seeds.dried_fruit",
 "dry nuts": "nuts_seeds.nuts",
 "nut butter": "nuts_seeds.nut_butters",
 "biscuit": "snacks.biscuits_cookies",
 "biscuits": "snacks.biscuits_cookies",
 "cookie": "snacks.biscuits_cookies",
 "cookies": "snacks.biscuits_cookies",
 "chips": "snacks.chips_crisps",
 "crisps": "snacks.chips_crisps",
 "wafers": "snacks.chips_crisps",
 "whey": "supplements.protein_powder",
 "chocolates": "sweets.chocolate",
 "dark chocolate": "sweets.chocolate",
 "cereal": "staples.breakfast_cereals",
 "cereals": "staples.breakfast_cereals",
 "muesli": "staples.breakfast_cereals",
 "granola": "staples.breakfast_cereals",
 "mixture": "snacks.namkeen",
 "bhujia": "snacks.namkeen",
 "sev": "snacks.namkeen",
 "farsan": "snacks.namkeen",
 "pulses": "staples.pulses",
 "poha": "staples.rice",
 "flour": "staples.flours",
 "wheat": "staples.flours",
 "whole wheat": "staples.flours",
 "wheat flour": "staples.flours",
 "chakki": "staples.flours"
});

export const FOOD_WORDS_VERSION = "778w-32c";
